import mods.modularmachinery.RecipeBuilder;
import crafttweaker.formatting.IFormattedText;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import crafttweaker.data.IData;
import crafttweaker.enchantments.IEnchantment;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.oredict.IOreDict;
import mods.buildcraft.AssemblyTable;
import mods.thaumcraft.Infusion;
import mods.thermalexpansion.InductionSmelter;
import mods.thermalexpansion.Compactor;
import mods.thermalexpansion.Transposer;
import mods.enderio.Vat;

//ctgui craftingtable
//mods.industrialupgrade.AdvAlloySmelter.addRecipe(output, container, fill, fill1, temperature);
//mods.industrialupgrade.Fermer.addRecipe(output, container);
//industrialupgrade.AlloySmelter.addRecipe(output, container, fill, temperature);
//mods.industrialupgrade.MatterRecipe.addRecipe(output, matter, sunmatter, aquamatter, nethermatter, nightmatter, earthmatter, endmatter, aermatter);
//mods.industrialupgrade.UURecipe.addRecipe(output, col);
//liquid sword6




//Амулет: Хаос кристалл
mods.thaumcraft.Infusion.registerRecipe("chaos_diamond", "",  <contenttweaker:chaos_diamond>, 10, [<aspect:desiderium> * 1024,<aspect:mortuus> * 512,<aspect:tenebrae> * 512,<aspect:auram> * 512,<aspect:alkimia> * 512,<aspect:exanimis> * 512], <contenttweaker:compressed_redstone_block_x4>, [<divinerpg:corrupted_stone>,<divinerpg:bluefire_stone>,<divinerpg:ice_stone>,<divinerpg:jungle_stone>,<divinerpg:terran_stone>,<divinerpg:divine_stone>,<divinerpg:molten_stone>,<divinerpg:bloodgem>,<divinerpg:ender_stone>,<divinerpg:healing_stone>,<divinerpg:shadow_stone>]);

//Амулет:череп кошмаров
recipes.addShaped(<contenttweaker:skull_of_nightmares>, [[<divinerpg:rock_chunks>, <divinerpg:acid>, <divinerpg:honeychunk>],[<divinerpg:polished_pearls>, <divinerpg:quadrotic_lump>, <divinerpg:polished_pearls>], [<divinerpg:honeychunk>, <divinerpg:acid>, <divinerpg:rock_chunks>]]);

//Блок космиума
recipes.addShaped(<contenttweaker:cosmium_block>, [[<contenttweaker:cosmium_ingot>, <contenttweaker:cosmium_ingot>, <contenttweaker:cosmium_ingot>],[<contenttweaker:cosmium_ingot>, <contenttweaker:cosmium_ingot>, <contenttweaker:cosmium_ingot>], [<contenttweaker:cosmium_ingot>, <contenttweaker:cosmium_ingot>, <contenttweaker:cosmium_ingot>]]);

//Схема
recipes.addShaped(<contenttweaker:circuit1>, [[<thermalfoundation:material:192>, <contenttweaker:circuit>, <thermalfoundation:material:192>],[<contenttweaker:copper_stick>, <ore:plateIron>, <contenttweaker:copper_stick>], [<thermalfoundation:material:192>, <contenttweaker:circuit>, <thermalfoundation:material:192>]]);

//Микро схема
recipes.addShaped(<contenttweaker:circuit>, [[<minecraft:gold_nugget>, <minecraft:paper>, <minecraft:gold_nugget>],[<industrialupgrade:crafting_elements:271>, <minecraft:redstone>, <industrialupgrade:crafting_elements:271>], [<minecraft:gold_nugget>, <minecraft:paper>, <minecraft:gold_nugget>]]);

//Распределитель жидкостей: Кислотный хаотический слиток
mods.thermalexpansion.Transposer.addFillRecipe(<contenttweaker:acid_chaotic_ingot>,<industrialupgrade:chaosingot>, <liquid:acid> * 5000, 100000);

//Химическая смесь
recipes.addShapeless(<contenttweaker:chemical_mixture>, [<minecraft:clay_ball>,<minecraft:flint>,<minecraft:gunpowder>,<minecraft:paper>]);

//Биомасса
recipes.addShapeless(<contenttweaker:biomass>, [<contenttweaker:cockroach>,<contenttweaker:tarantula>,<contenttweaker:salpuga>,<contenttweaker:scorpion>,<contenttweaker:stag_beetle>,<contenttweaker:centipede>,<contenttweaker:mantis>,<contenttweaker:cuckold_beetle>]);

//Медный стержень
recipes.addShaped(<contenttweaker:copper_stick>, [[null, null, null],[null, <thermalfoundation:material:320>, null], [null, <thermalfoundation:material:320>, null]]);
mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:copper_stick>, <thermalfoundation:material:320>, 5000);

//Дракониевый стержень
recipes.addShaped(<contenttweaker:draconium_rod>, [[null, null, null],[null, <contenttweaker:draconium_plate>, null], [null, <contenttweaker:draconium_plate>, null]]);


mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:draconium_plate>, <draconicevolution:draconium_ingot>, 5000);
mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:draconium_gear>, <contenttweaker:draconium_plate>*4, 5000);
mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:awakened_draconium_plate>, <draconicevolution:draconic_ingot>, 5000);
mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:awakened_draconium_gear>, <contenttweaker:awakened_draconium_plate>*4, 5000);
mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:alloy_awakened_draconium_plate>, <contenttweaker:alloy_awakened_draconium_ingot>, 5000);
mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:alloy_awakened_draconium_gear>, <contenttweaker:alloy_awakened_draconium_plate>*4, 5000);
mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:plate1>, <contenttweaker:ingot_of_dragon_shadow_steel>, 5000);
mods.thermalexpansion.Compactor.addPressRecipe(<contenttweaker:plate2>, <contenttweaker:plate1>*9, 5000);
recipes.addShaped(<contenttweaker:dragon_item>, [[<contenttweaker:draconium_plate>, <contenttweaker:dragon_circuit>, <contenttweaker:draconium_plate>],[<contenttweaker:dragon_iridium>, <industrialupgrade:spectral_box>, <contenttweaker:dragon_iridium>], [<contenttweaker:draconium_plate>, <contenttweaker:dragon_circuit>, <contenttweaker:draconium_plate>]]);
recipes.addShaped(<contenttweaker:dragon_item2>, [[<contenttweaker:plate2>, <contenttweaker:dragon_item>, <contenttweaker:plate2>],[<contenttweaker:dragon_ichor_ingot>, <industrialupgrade:adv_spectral_box>, <contenttweaker:dragon_ichor_ingot>], [<contenttweaker:plate2>, <contenttweaker:dragon_item>, <contenttweaker:plate2>]]);
recipes.addShaped(<contenttweaker:dragon_item4>, [[<avaritia:resource:4>, <contenttweaker:dragon_item3>, <contenttweaker:awakened_draconium_gear>],[<industrialupgrade:itemsunnariumpanel:3>, <contenttweaker:dragon_item2>, <industrialupgrade:itemsunnariumpanel:3>], [<contenttweaker:awakened_draconium_gear>, <contenttweaker:dragon_item3>, <avaritia:resource:4>]]);
recipes.addShaped(<contenttweaker:dragon_item3>, [[<contenttweaker:awakened_draconium_plate>, <contenttweaker:dragon_circuit>, <contenttweaker:awakened_draconium_plate>],[<bigreactors:ingotludicrite>, <contenttweaker:dragon_item>, <bigreactors:ingotludicrite>], [<contenttweaker:awakened_draconium_plate>, <contenttweaker:dragon_circuit>, <contenttweaker:awakened_draconium_plate>]]);
mods.industrialupgrade.GenMicrochip.addRecipe(<contenttweaker:dragon_circuit>, <bigreactors:ingotgraphite>, <draconicevolution:draconic_core>, <contenttweaker:dragon_part3>, <contenttweaker:dragon_part2>, <contenttweaker:dragon_part1>, 5000);
recipes.addShapeless(<contenttweaker:infinity_nugget> * 9, [<avaritia:resource:6>]);
recipes.addShaped(<contenttweaker:dragon_machine_frame>, [[<galaxyspace:hdp>, <draconicevolution:draconic_core>, <galaxyspace:hdp>],[<draconicevolution:draconic_core>, <extrautils2:machine>, <draconicevolution:draconic_core>], [<galaxyspace:hdp>, <draconicevolution:draconic_core>, <galaxyspace:hdp>]]);
recipes.addShaped(<contenttweaker:transmutation_casing>, [[<contenttweaker:otherworldly_charging_element>, <projecte:item.pe_matter>, <contenttweaker:otherworldly_charging_element>],[<projecte:item.pe_matter>, <contenttweaker:dragon_machine_frame>, <projecte:item.pe_matter>], [<contenttweaker:otherworldly_charging_element>, <projecte:item.pe_matter>, <contenttweaker:otherworldly_charging_element>]]);
mods.thaumcraft.Infusion.registerRecipe("ultra_casing", "", <contenttweaker:ultra_casing>, 15, [<aspect:basium> * 256,  <aspect:metallum> * 128,<aspect:praecantatio> * 128], <contenttweaker:dragon_machine_frame>, [<bigreactors:blockludicrite>,<avaritia:resource>,<bigreactors:blockludicrite>,<avaritia:resource>,<bigreactors:blockludicrite>,<avaritia:resource>,<bigreactors:blockludicrite>,<avaritia:resource>]);
recipes.addShaped(<contenttweaker:chaos_casing>, [[<contenttweaker:awakened_draconium_plate>, <draconicevolution:chaos_shard:3>, <contenttweaker:awakened_draconium_plate>],[<draconicevolution:chaos_shard:3>, <contenttweaker:dragon_machine_frame>, <draconicevolution:chaos_shard:3>], [<contenttweaker:awakened_draconium_plate>, <draconicevolution:chaos_shard:3>, <contenttweaker:awakened_draconium_plate>]]);
recipes.addShaped(<contenttweaker:glass_of_the_last_smeltery>, [[<contenttweaker:last_casing>, <industrialupgrade:glass>, <contenttweaker:last_casing>],[<industrialupgrade:glass>, <thermalfoundation:glass_alloy:7>, <industrialupgrade:glass>], [<contenttweaker:last_casing>, <industrialupgrade:glass>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:pc_device_of_the_last_smeltery>, [[<contenttweaker:last_casing>, <industrialupgrade:crafting_elements:127>, <contenttweaker:last_casing>],[<industrialupgrade:crafting_elements:223>, <modularmachinery:blockcasing:5>, <industrialupgrade:crafting_elements:110>], [<contenttweaker:last_casing>, <industrialupgrade:crafting_elements:136>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:ventilation_of_the_last_smeltery>, [[<contenttweaker:last_casing>, <industrialupgrade:crafting_elements:107>, <contenttweaker:last_casing>],[<industrialupgrade:crafting_elements:173>, <modularmachinery:blockcasing:1>, <industrialupgrade:crafting_elements:173>], [<contenttweaker:last_casing>, <industrialupgrade:crafting_elements:107>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:heater_of_the_last_smeltery>, [[<contenttweaker:last_casing>, <industrialupgrade:crafting_elements:115>, <contenttweaker:last_casing>],[<industrialupgrade:crafting_elements:114>, <modularmachinery:blockcasing:2>, <industrialupgrade:crafting_elements:114>], [<contenttweaker:last_casing>, <industrialupgrade:crafting_elements:115>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:injector_of_the_last_forge>, [[<contenttweaker:last_casing>, <draconicevolution:crafting_injector>, <contenttweaker:last_casing>],[<draconicevolution:crafting_injector>, <modularmachinery:blockcasing>, <draconicevolution:crafting_injector>], [<contenttweaker:last_casing>, <draconicevolution:crafting_injector>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:frame_of_the_last_forge>, [[<contenttweaker:last_casing>, <divinerpg:arcana_portal_frame>, <contenttweaker:last_casing>],[<divinerpg:arcana_portal_frame>, <divinerpg:mortum_block>, <divinerpg:arcana_portal_frame>], [<contenttweaker:last_casing>, <divinerpg:arcana_portal_frame>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:trophy_of_the_last_forge>, [[<contenttweaker:last_casing>, <variedcommodities:statuette>, <contenttweaker:last_casing>],[<variedcommodities:statuette>, <modularmachinery:blockcasing>, <variedcommodities:statuette>], [<contenttweaker:last_casing>, <variedcommodities:statuette>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:stabilizer_of_the_last_forge>, [[<contenttweaker:last_casing>, <galaxyspace:rocket_parts:19>, <contenttweaker:last_casing>],[<thaumcraft:stabilizer>, <draconicevolution:particle_generator:2>, <thaumcraft:stabilizer>], [<contenttweaker:last_casing>, <galaxyspace:rocket_parts:19>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:transformer_of_the_last_forge>, [[<contenttweaker:last_casing>, <industrialupgrade:crafting_elements:215>, <contenttweaker:last_casing>],[<industrialupgrade:crafting_elements:216>, <industrialupgrade:upgrades:3>, <industrialupgrade:crafting_elements:214>], [<contenttweaker:last_casing>, <industrialupgrade:crafting_elements:213>, <contenttweaker:last_casing>]]);
recipes.addShaped(<contenttweaker:neutronium_taco>, [[<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>],[<avaritia:resource:3>, <contenttweaker:taco>, <avaritia:resource:3>], [<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>]]);
recipes.addShaped(<contenttweaker:neutronium_burger>, [[<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>],[<avaritia:resource:3>, <contenttweaker:burger>, <avaritia:resource:3>], [<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>]]);
recipes.addShaped(<contenttweaker:neutronium_sausage_roll>, [[<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>],[<avaritia:resource:3>, <contenttweaker:sausage_roll>, <avaritia:resource:3>], [<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>]]);
recipes.addShaped(<contenttweaker:neutronium_pizza>, [[<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>],[<avaritia:resource:3>, <contenttweaker:pizza>, <avaritia:resource:3>], [<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>]]);
recipes.addShaped(<contenttweaker:alloy_awakened_draconium_block>, [[<contenttweaker:alloy_awakened_draconium_ingot>, <contenttweaker:alloy_awakened_draconium_ingot>, <contenttweaker:alloy_awakened_draconium_ingot>],[<contenttweaker:alloy_awakened_draconium_ingot>, <contenttweaker:alloy_awakened_draconium_ingot>, <contenttweaker:alloy_awakened_draconium_ingot>], [<contenttweaker:alloy_awakened_draconium_ingot>, <contenttweaker:alloy_awakened_draconium_ingot>, <contenttweaker:alloy_awakened_draconium_ingot>]]);
recipes.addShaped(<contenttweaker:tunshilinonim_block>, [[<contenttweaker:tunshilinonim_ingot>, <contenttweaker:tunshilinonim_ingot>, <contenttweaker:tunshilinonim_ingot>],[<contenttweaker:tunshilinonim_ingot>, <contenttweaker:tunshilinonim_ingot>, <contenttweaker:tunshilinonim_ingot>], [<contenttweaker:tunshilinonim_ingot>, <contenttweaker:tunshilinonim_ingot>, <contenttweaker:tunshilinonim_ingot>]]);
recipes.addShaped(<contenttweaker:demonic_metal_block>, [[<contenttweaker:demonic_metal_ingot>, <contenttweaker:demonic_metal_ingot>, <contenttweaker:demonic_metal_ingot>],[<contenttweaker:demonic_metal_ingot>, <contenttweaker:demonic_metal_ingot>, <contenttweaker:demonic_metal_ingot>], [<contenttweaker:demonic_metal_ingot>, <contenttweaker:demonic_metal_ingot>, <contenttweaker:demonic_metal_ingot>]]);
recipes.addShaped(<contenttweaker:stable_unstable_block>, [[<extrautils2:unstableingots:2>, <extrautils2:unstableingots:2>, <extrautils2:unstableingots:2>],[<extrautils2:unstableingots:2>, <extrautils2:unstableingots:2>, <extrautils2:unstableingots:2>], [<extrautils2:unstableingots:2>, <extrautils2:unstableingots:2>, <extrautils2:unstableingots:2>]]);
recipes.addShaped(<contenttweaker:dragon_part1>, [[<industrialupgrade:itemplates:10>, <enderio:item_basic_capacitor:2>, <industrialupgrade:itemplates:10>],[<contenttweaker:dragon_part3>, <industrialupgrade:circuit:11>, <contenttweaker:dragon_part3>], [<industrialupgrade:itemplates:3>, <industrialupgrade:compresscarbon>, <industrialupgrade:itemplates:3>]]);
recipes.addShaped(<contenttweaker:dragon_part2>, [[<contenttweaker:draconium_rod>, <contenttweaker:draconium_rod>, <contenttweaker:draconium_rod>],[<contenttweaker:draconium_rod>, <contenttweaker:dragon_part3>, <contenttweaker:draconium_rod>], [<contenttweaker:draconium_rod>, <contenttweaker:draconium_rod>, <contenttweaker:draconium_rod>]]);
recipes.addShaped(<contenttweaker:pot>, [[<industrialupgrade:baseblockingot:3>, <industrialupgrade:baseblockingot:3>, <industrialupgrade:baseblockingot:3>],[<industrialupgrade:baseblockingot:3>, <minecraft:cauldron>, <industrialupgrade:baseblockingot:3>], [<industrialupgrade:baseblockingot:3>, <industrialupgrade:baseblockingot:3>, <industrialupgrade:baseblockingot:3>]]);
recipes.addShaped(<contenttweaker:the_mendeleev_core>, [[<contenttweaker:nuclear_fusion_reactor_casing>, <contenttweaker:alchemical_core>, <contenttweaker:nuclear_fusion_reactor_casing>],[<contenttweaker:alchemical_core>, <contenttweaker:rose_gold_ingot>, <contenttweaker:alchemical_core>], [<contenttweaker:nuclear_fusion_reactor_casing>, <contenttweaker:alchemical_core>, <contenttweaker:nuclear_fusion_reactor_casing>]]);
recipes.addShaped(<contenttweaker:chaotic_block>, [[<industrialupgrade:chaosingot>, <industrialupgrade:chaosingot>, <industrialupgrade:chaosingot>],[<industrialupgrade:chaosingot>, <industrialupgrade:chaosingot>, <industrialupgrade:chaosingot>], [<industrialupgrade:chaosingot>, <industrialupgrade:chaosingot>, <industrialupgrade:chaosingot>]]);

recipes.addShaped(<contenttweaker:compressed_gold_block_x1>, [[<minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>],[<minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>], [<minecraft:gold_block>, <minecraft:gold_block>, <minecraft:gold_block>]]);
recipes.addShaped(<contenttweaker:compressed_iron_block_x1>, [[<minecraft:iron_block>, <minecraft:iron_block>, <minecraft:iron_block>],[<minecraft:iron_block>, <minecraft:iron_block>, <minecraft:iron_block>], [<minecraft:iron_block>, <minecraft:iron_block>, <minecraft:iron_block>]]);
recipes.addShaped(<contenttweaker:compressed_diamond_block_x1>, [[<minecraft:diamond_block>, <minecraft:diamond_block>, <minecraft:diamond_block>],[<minecraft:diamond_block>, <minecraft:diamond_block>, <minecraft:diamond_block>], [<minecraft:diamond_block>, <minecraft:diamond_block>, <minecraft:diamond_block>]]);

//Золотые блоки
recipes.addShapeless(<minecraft:gold_block> * 9, [<contenttweaker:compressed_gold_block_x1>]);
recipes.addShapeless(<contenttweaker:compressed_gold_block_x1> * 9, [<contenttweaker:compressed_gold_block_x2>]);
recipes.addShapeless(<contenttweaker:compressed_gold_block_x2> * 9, [<contenttweaker:compressed_gold_block_x3>]);
recipes.addShapeless(<contenttweaker:compressed_gold_block_x3> * 9, [<contenttweaker:compressed_gold_block_x4>]);
recipes.addShapeless(<contenttweaker:compressed_gold_block_x4> * 9, [<contenttweaker:compressed_gold_block_x5>]);
recipes.addShapeless(<contenttweaker:compressed_gold_block_x5> * 9, [<contenttweaker:compressed_gold_block_x6>]);
recipes.addShapeless(<contenttweaker:compressed_gold_block_x6> * 9, [<contenttweaker:compressed_gold_block_x7>]);
recipes.addShapeless(<contenttweaker:compressed_gold_block_x7> * 9, [<contenttweaker:compressed_gold_block_x8>]);
recipes.addShaped(<contenttweaker:compressed_gold_block_x8>, [[<contenttweaker:compressed_gold_block_x7>, <contenttweaker:compressed_gold_block_x7>, <contenttweaker:compressed_gold_block_x7>],[<contenttweaker:compressed_gold_block_x7>, <contenttweaker:compressed_gold_block_x7>, <contenttweaker:compressed_gold_block_x7>], [<contenttweaker:compressed_gold_block_x7>, <contenttweaker:compressed_gold_block_x7>, <contenttweaker:compressed_gold_block_x7>]]);
recipes.addShaped(<contenttweaker:compressed_gold_block_x7>, [[<contenttweaker:compressed_gold_block_x6>, <contenttweaker:compressed_gold_block_x6>, <contenttweaker:compressed_gold_block_x6>],[<contenttweaker:compressed_gold_block_x6>, <contenttweaker:compressed_gold_block_x6>, <contenttweaker:compressed_gold_block_x6>], [<contenttweaker:compressed_gold_block_x6>, <contenttweaker:compressed_gold_block_x6>, <contenttweaker:compressed_gold_block_x6>]]);
recipes.addShaped(<contenttweaker:compressed_gold_block_x6>, [[<contenttweaker:compressed_gold_block_x5>, <contenttweaker:compressed_gold_block_x5>, <contenttweaker:compressed_gold_block_x5>],[<contenttweaker:compressed_gold_block_x5>, <contenttweaker:compressed_gold_block_x5>, <contenttweaker:compressed_gold_block_x5>], [<contenttweaker:compressed_gold_block_x5>, <contenttweaker:compressed_gold_block_x5>, <contenttweaker:compressed_gold_block_x5>]]);
recipes.addShaped(<contenttweaker:compressed_gold_block_x5>, [[<contenttweaker:compressed_gold_block_x4>, <contenttweaker:compressed_gold_block_x4>, <contenttweaker:compressed_gold_block_x4>],[<contenttweaker:compressed_gold_block_x4>, <contenttweaker:compressed_gold_block_x4>, <contenttweaker:compressed_gold_block_x4>], [<contenttweaker:compressed_gold_block_x4>, <contenttweaker:compressed_gold_block_x4>, <contenttweaker:compressed_gold_block_x4>]]);
recipes.addShaped(<contenttweaker:compressed_gold_block_x4>, [[<contenttweaker:compressed_gold_block_x3>, <contenttweaker:compressed_gold_block_x3>, <contenttweaker:compressed_gold_block_x3>],[<contenttweaker:compressed_gold_block_x3>, <contenttweaker:compressed_gold_block_x3>, <contenttweaker:compressed_gold_block_x3>], [<contenttweaker:compressed_gold_block_x3>, <contenttweaker:compressed_gold_block_x3>, <contenttweaker:compressed_gold_block_x3>]]);
recipes.addShaped(<contenttweaker:compressed_gold_block_x3>, [[<contenttweaker:compressed_gold_block_x2>, <contenttweaker:compressed_gold_block_x2>, <contenttweaker:compressed_gold_block_x2>],[<contenttweaker:compressed_gold_block_x2>, <contenttweaker:compressed_gold_block_x2>, <contenttweaker:compressed_gold_block_x2>], [<contenttweaker:compressed_gold_block_x2>, <contenttweaker:compressed_gold_block_x2>, <contenttweaker:compressed_gold_block_x2>]]);
recipes.addShaped(<contenttweaker:compressed_gold_block_x2>, [[<contenttweaker:compressed_gold_block_x1>, <contenttweaker:compressed_gold_block_x1>, <contenttweaker:compressed_gold_block_x1>],[<contenttweaker:compressed_gold_block_x1>, <contenttweaker:compressed_gold_block_x1>, <contenttweaker:compressed_gold_block_x1>], [<contenttweaker:compressed_gold_block_x1>, <contenttweaker:compressed_gold_block_x1>, <contenttweaker:compressed_gold_block_x1>]]);

//Алмазные блоки
recipes.addShapeless(<minecraft:diamond_block> * 9, [<contenttweaker:compressed_diamond_block_x1>]);
recipes.addShapeless(<contenttweaker:compressed_diamond_block_x1> * 9, [<contenttweaker:compressed_diamond_block_x2>]);
recipes.addShapeless(<contenttweaker:compressed_diamond_block_x2> * 9, [<contenttweaker:compressed_diamond_block_x3>]);
recipes.addShapeless(<contenttweaker:compressed_diamond_block_x3> * 9, [<contenttweaker:compressed_diamond_block_x4>]);
recipes.addShapeless(<contenttweaker:compressed_diamond_block_x4> * 9, [<contenttweaker:compressed_diamond_block_x5>]);
recipes.addShapeless(<contenttweaker:compressed_diamond_block_x5> * 9, [<contenttweaker:compressed_diamond_block_x6>]);
recipes.addShapeless(<contenttweaker:compressed_diamond_block_x6> * 9, [<contenttweaker:compressed_diamond_block_x7>]);
recipes.addShapeless(<contenttweaker:compressed_diamond_block_x7> * 9, [<contenttweaker:compressed_diamond_block_x8>]);
recipes.addShaped(<contenttweaker:compressed_diamond_block_x8>, [[<contenttweaker:compressed_diamond_block_x7>, <contenttweaker:compressed_diamond_block_x7>, <contenttweaker:compressed_diamond_block_x7>],[<contenttweaker:compressed_diamond_block_x7>, <contenttweaker:compressed_diamond_block_x7>, <contenttweaker:compressed_diamond_block_x7>], [<contenttweaker:compressed_diamond_block_x7>, <contenttweaker:compressed_diamond_block_x7>, <contenttweaker:compressed_diamond_block_x7>]]);
recipes.addShaped(<contenttweaker:compressed_diamond_block_x7>, [[<contenttweaker:compressed_diamond_block_x6>, <contenttweaker:compressed_diamond_block_x6>, <contenttweaker:compressed_diamond_block_x6>],[<contenttweaker:compressed_diamond_block_x6>, <contenttweaker:compressed_diamond_block_x6>, <contenttweaker:compressed_diamond_block_x6>], [<contenttweaker:compressed_diamond_block_x6>, <contenttweaker:compressed_diamond_block_x6>, <contenttweaker:compressed_diamond_block_x6>]]);
recipes.addShaped(<contenttweaker:compressed_diamond_block_x6>, [[<contenttweaker:compressed_diamond_block_x5>, <contenttweaker:compressed_diamond_block_x5>, <contenttweaker:compressed_diamond_block_x5>],[<contenttweaker:compressed_diamond_block_x5>, <contenttweaker:compressed_diamond_block_x5>, <contenttweaker:compressed_diamond_block_x5>], [<contenttweaker:compressed_diamond_block_x5>, <contenttweaker:compressed_diamond_block_x5>, <contenttweaker:compressed_diamond_block_x5>]]);
recipes.addShaped(<contenttweaker:compressed_diamond_block_x5>, [[<contenttweaker:compressed_diamond_block_x4>, <contenttweaker:compressed_diamond_block_x4>, <contenttweaker:compressed_diamond_block_x4>],[<contenttweaker:compressed_diamond_block_x4>, <contenttweaker:compressed_diamond_block_x4>, <contenttweaker:compressed_diamond_block_x4>], [<contenttweaker:compressed_diamond_block_x4>, <contenttweaker:compressed_diamond_block_x4>, <contenttweaker:compressed_diamond_block_x4>]]);
recipes.addShaped(<contenttweaker:compressed_diamond_block_x4>, [[<contenttweaker:compressed_diamond_block_x3>, <contenttweaker:compressed_diamond_block_x3>, <contenttweaker:compressed_diamond_block_x3>],[<contenttweaker:compressed_diamond_block_x3>, <contenttweaker:compressed_diamond_block_x3>, <contenttweaker:compressed_diamond_block_x3>], [<contenttweaker:compressed_diamond_block_x3>, <contenttweaker:compressed_diamond_block_x3>, <contenttweaker:compressed_diamond_block_x3>]]);
recipes.addShaped(<contenttweaker:compressed_diamond_block_x3>, [[<contenttweaker:compressed_diamond_block_x2>, <contenttweaker:compressed_diamond_block_x2>, <contenttweaker:compressed_diamond_block_x2>],[<contenttweaker:compressed_diamond_block_x2>, <contenttweaker:compressed_diamond_block_x2>, <contenttweaker:compressed_diamond_block_x2>], [<contenttweaker:compressed_diamond_block_x2>, <contenttweaker:compressed_diamond_block_x2>, <contenttweaker:compressed_diamond_block_x2>]]);
recipes.addShaped(<contenttweaker:compressed_diamond_block_x2>, [[<contenttweaker:compressed_diamond_block_x1>, <contenttweaker:compressed_diamond_block_x1>, <contenttweaker:compressed_diamond_block_x1>],[<contenttweaker:compressed_diamond_block_x1>, <contenttweaker:compressed_diamond_block_x1>, <contenttweaker:compressed_diamond_block_x1>], [<contenttweaker:compressed_diamond_block_x1>, <contenttweaker:compressed_diamond_block_x1>, <contenttweaker:compressed_diamond_block_x1>]]);

//Железные блоки
recipes.addShapeless(<minecraft:iron_block> * 9, [<contenttweaker:compressed_iron_block_x1>]);
recipes.addShapeless(<contenttweaker:compressed_iron_block_x1> * 9, [<contenttweaker:compressed_iron_block_x2>]);
recipes.addShapeless(<contenttweaker:compressed_iron_block_x2> * 9, [<contenttweaker:compressed_iron_block_x3>]);
recipes.addShapeless(<contenttweaker:compressed_iron_block_x3> * 9, [<contenttweaker:compressed_iron_block_x4>]);
recipes.addShapeless(<contenttweaker:compressed_iron_block_x4> * 9, [<contenttweaker:compressed_iron_block_x5>]);
recipes.addShapeless(<contenttweaker:compressed_iron_block_x5> * 9, [<contenttweaker:compressed_iron_block_x6>]);
recipes.addShapeless(<contenttweaker:compressed_iron_block_x6> * 9, [<contenttweaker:compressed_iron_block_x7>]);
recipes.addShapeless(<contenttweaker:compressed_iron_block_x7> * 9, [<contenttweaker:compressed_iron_block_x8>]);
recipes.addShaped(<contenttweaker:compressed_iron_block_x8>, [[<contenttweaker:compressed_iron_block_x7>, <contenttweaker:compressed_iron_block_x7>, <contenttweaker:compressed_iron_block_x7>],[<contenttweaker:compressed_iron_block_x7>, <contenttweaker:compressed_iron_block_x7>, <contenttweaker:compressed_iron_block_x7>], [<contenttweaker:compressed_iron_block_x7>, <contenttweaker:compressed_iron_block_x7>, <contenttweaker:compressed_iron_block_x7>]]);
recipes.addShaped(<contenttweaker:compressed_iron_block_x7>, [[<contenttweaker:compressed_iron_block_x6>, <contenttweaker:compressed_iron_block_x6>, <contenttweaker:compressed_iron_block_x6>],[<contenttweaker:compressed_iron_block_x6>, <contenttweaker:compressed_iron_block_x6>, <contenttweaker:compressed_iron_block_x6>], [<contenttweaker:compressed_iron_block_x6>, <contenttweaker:compressed_iron_block_x6>, <contenttweaker:compressed_iron_block_x6>]]);
recipes.addShaped(<contenttweaker:compressed_iron_block_x6>, [[<contenttweaker:compressed_iron_block_x5>, <contenttweaker:compressed_iron_block_x5>, <contenttweaker:compressed_iron_block_x5>],[<contenttweaker:compressed_iron_block_x5>, <contenttweaker:compressed_iron_block_x5>, <contenttweaker:compressed_iron_block_x5>], [<contenttweaker:compressed_iron_block_x5>, <contenttweaker:compressed_iron_block_x5>, <contenttweaker:compressed_iron_block_x5>]]);
recipes.addShaped(<contenttweaker:compressed_iron_block_x5>, [[<contenttweaker:compressed_iron_block_x4>, <contenttweaker:compressed_iron_block_x4>, <contenttweaker:compressed_iron_block_x4>],[<contenttweaker:compressed_iron_block_x4>, <contenttweaker:compressed_iron_block_x4>, <contenttweaker:compressed_iron_block_x4>], [<contenttweaker:compressed_iron_block_x4>, <contenttweaker:compressed_iron_block_x4>, <contenttweaker:compressed_iron_block_x4>]]);
recipes.addShaped(<contenttweaker:compressed_iron_block_x4>, [[<contenttweaker:compressed_iron_block_x3>, <contenttweaker:compressed_iron_block_x3>, <contenttweaker:compressed_iron_block_x3>],[<contenttweaker:compressed_iron_block_x3>, <contenttweaker:compressed_iron_block_x3>, <contenttweaker:compressed_iron_block_x3>], [<contenttweaker:compressed_iron_block_x3>, <contenttweaker:compressed_iron_block_x3>, <contenttweaker:compressed_iron_block_x3>]]);
recipes.addShaped(<contenttweaker:compressed_iron_block_x3>, [[<contenttweaker:compressed_iron_block_x2>, <contenttweaker:compressed_iron_block_x2>, <contenttweaker:compressed_iron_block_x2>],[<contenttweaker:compressed_iron_block_x2>, <contenttweaker:compressed_iron_block_x2>, <contenttweaker:compressed_iron_block_x2>], [<contenttweaker:compressed_iron_block_x2>, <contenttweaker:compressed_iron_block_x2>, <contenttweaker:compressed_iron_block_x2>]]);
recipes.addShaped(<contenttweaker:compressed_iron_block_x2>, [[<contenttweaker:compressed_iron_block_x1>, <contenttweaker:compressed_iron_block_x1>, <contenttweaker:compressed_iron_block_x1>],[<contenttweaker:compressed_iron_block_x1>, <contenttweaker:compressed_iron_block_x1>, <contenttweaker:compressed_iron_block_x1>], [<contenttweaker:compressed_iron_block_x1>, <contenttweaker:compressed_iron_block_x1>, <contenttweaker:compressed_iron_block_x1>]]);

//Лазуритные блоки
recipes.addShapeless(<minecraft:lapis_block> * 9, [<contenttweaker:compressed_lapis_block_x1>]);
recipes.addShapeless(<contenttweaker:compressed_lapis_block_x1> * 9, [<contenttweaker:compressed_lapis_block_x2>]);
recipes.addShapeless(<contenttweaker:compressed_lapis_block_x2> * 9, [<contenttweaker:compressed_lapis_block_x3>]);
recipes.addShapeless(<contenttweaker:compressed_lapis_block_x3> * 9, [<contenttweaker:compressed_lapis_block_x4>]);
recipes.addShapeless(<contenttweaker:compressed_lapis_block_x4> * 9, [<contenttweaker:compressed_lapis_block_x5>]);
recipes.addShapeless(<contenttweaker:compressed_lapis_block_x5> * 9, [<contenttweaker:compressed_lapis_block_x6>]);
recipes.addShapeless(<contenttweaker:compressed_lapis_block_x6> * 9, [<contenttweaker:compressed_lapis_block_x7>]);
recipes.addShapeless(<contenttweaker:compressed_lapis_block_x7> * 9, [<contenttweaker:compressed_lapis_block_x8>]);
recipes.addShaped(<contenttweaker:compressed_lapis_block_x8>, [[<contenttweaker:compressed_lapis_block_x7>, <contenttweaker:compressed_lapis_block_x7>, <contenttweaker:compressed_lapis_block_x7>],[<contenttweaker:compressed_lapis_block_x7>, <contenttweaker:compressed_lapis_block_x7>, <contenttweaker:compressed_lapis_block_x7>], [<contenttweaker:compressed_lapis_block_x7>, <contenttweaker:compressed_lapis_block_x7>, <contenttweaker:compressed_lapis_block_x7>]]);
recipes.addShaped(<contenttweaker:compressed_lapis_block_x7>, [[<contenttweaker:compressed_lapis_block_x6>, <contenttweaker:compressed_lapis_block_x6>, <contenttweaker:compressed_lapis_block_x6>],[<contenttweaker:compressed_lapis_block_x6>, <contenttweaker:compressed_lapis_block_x6>, <contenttweaker:compressed_lapis_block_x6>], [<contenttweaker:compressed_lapis_block_x6>, <contenttweaker:compressed_lapis_block_x6>, <contenttweaker:compressed_lapis_block_x6>]]);
recipes.addShaped(<contenttweaker:compressed_lapis_block_x6>, [[<contenttweaker:compressed_lapis_block_x5>, <contenttweaker:compressed_lapis_block_x5>, <contenttweaker:compressed_lapis_block_x5>],[<contenttweaker:compressed_lapis_block_x5>, <contenttweaker:compressed_lapis_block_x5>, <contenttweaker:compressed_lapis_block_x5>], [<contenttweaker:compressed_lapis_block_x5>, <contenttweaker:compressed_lapis_block_x5>, <contenttweaker:compressed_lapis_block_x5>]]);
recipes.addShaped(<contenttweaker:compressed_lapis_block_x5>, [[<contenttweaker:compressed_lapis_block_x4>, <contenttweaker:compressed_lapis_block_x4>, <contenttweaker:compressed_lapis_block_x4>],[<contenttweaker:compressed_lapis_block_x4>, <contenttweaker:compressed_lapis_block_x4>, <contenttweaker:compressed_lapis_block_x4>], [<contenttweaker:compressed_lapis_block_x4>, <contenttweaker:compressed_lapis_block_x4>, <contenttweaker:compressed_lapis_block_x4>]]);
recipes.addShaped(<contenttweaker:compressed_lapis_block_x4>, [[<contenttweaker:compressed_lapis_block_x3>, <contenttweaker:compressed_lapis_block_x3>, <contenttweaker:compressed_lapis_block_x3>],[<contenttweaker:compressed_lapis_block_x3>, <contenttweaker:compressed_lapis_block_x3>, <contenttweaker:compressed_lapis_block_x3>], [<contenttweaker:compressed_lapis_block_x3>, <contenttweaker:compressed_lapis_block_x3>, <contenttweaker:compressed_lapis_block_x3>]]);
recipes.addShaped(<contenttweaker:compressed_lapis_block_x3>, [[<contenttweaker:compressed_lapis_block_x2>, <contenttweaker:compressed_lapis_block_x2>, <contenttweaker:compressed_lapis_block_x2>],[<contenttweaker:compressed_lapis_block_x2>, <contenttweaker:compressed_lapis_block_x2>, <contenttweaker:compressed_lapis_block_x2>], [<contenttweaker:compressed_lapis_block_x2>, <contenttweaker:compressed_lapis_block_x2>, <contenttweaker:compressed_lapis_block_x2>]]);
recipes.addShaped(<contenttweaker:compressed_lapis_block_x2>, [[<contenttweaker:compressed_lapis_block_x1>, <contenttweaker:compressed_lapis_block_x1>, <contenttweaker:compressed_lapis_block_x1>],[<contenttweaker:compressed_lapis_block_x1>, <contenttweaker:compressed_lapis_block_x1>, <contenttweaker:compressed_lapis_block_x1>], [<contenttweaker:compressed_lapis_block_x1>, <contenttweaker:compressed_lapis_block_x1>, <contenttweaker:compressed_lapis_block_x1>]]);
recipes.addShaped(<contenttweaker:compressed_lapis_block_x1>, [[<minecraft:lapis_block>, <minecraft:lapis_block>, <minecraft:lapis_block>],[<minecraft:lapis_block>, <minecraft:lapis_block>, <minecraft:lapis_block>], [<minecraft:lapis_block>, <minecraft:lapis_block>, <minecraft:lapis_block>]]);

//Редстоуновые блоки
recipes.addShapeless(<minecraft:redstone_block> * 9, [<contenttweaker:compressed_redstone_block_x1>]);
recipes.addShapeless(<contenttweaker:compressed_redstone_block_x1> * 9, [<contenttweaker:compressed_redstone_block_x2>]);
recipes.addShapeless(<contenttweaker:compressed_redstone_block_x2> * 9, [<contenttweaker:compressed_redstone_block_x3>]);
recipes.addShapeless(<contenttweaker:compressed_redstone_block_x3> * 9, [<contenttweaker:compressed_redstone_block_x4>]);
recipes.addShapeless(<contenttweaker:compressed_redstone_block_x4> * 9, [<contenttweaker:compressed_redstone_block_x5>]);
recipes.addShapeless(<contenttweaker:compressed_redstone_block_x5> * 9, [<contenttweaker:compressed_redstone_block_x6>]);
recipes.addShapeless(<contenttweaker:compressed_redstone_block_x6> * 9, [<contenttweaker:compressed_redstone_block_x7>]);
recipes.addShapeless(<contenttweaker:compressed_redstone_block_x7> * 9, [<contenttweaker:compressed_redstone_block_x8>]);
recipes.addShaped(<contenttweaker:compressed_redstone_block_x8>, [[<contenttweaker:compressed_redstone_block_x7>, <contenttweaker:compressed_redstone_block_x7>, <contenttweaker:compressed_redstone_block_x7>],[<contenttweaker:compressed_redstone_block_x7>, <contenttweaker:compressed_redstone_block_x7>, <contenttweaker:compressed_redstone_block_x7>], [<contenttweaker:compressed_redstone_block_x7>, <contenttweaker:compressed_redstone_block_x7>, <contenttweaker:compressed_redstone_block_x7>]]);
recipes.addShaped(<contenttweaker:compressed_redstone_block_x7>, [[<contenttweaker:compressed_redstone_block_x6>, <contenttweaker:compressed_redstone_block_x6>, <contenttweaker:compressed_redstone_block_x6>],[<contenttweaker:compressed_redstone_block_x6>, <contenttweaker:compressed_redstone_block_x6>, <contenttweaker:compressed_redstone_block_x6>], [<contenttweaker:compressed_redstone_block_x6>, <contenttweaker:compressed_redstone_block_x6>, <contenttweaker:compressed_redstone_block_x6>]]);
recipes.addShaped(<contenttweaker:compressed_redstone_block_x6>, [[<contenttweaker:compressed_redstone_block_x5>, <contenttweaker:compressed_redstone_block_x5>, <contenttweaker:compressed_redstone_block_x5>],[<contenttweaker:compressed_redstone_block_x5>, <contenttweaker:compressed_redstone_block_x5>, <contenttweaker:compressed_redstone_block_x5>], [<contenttweaker:compressed_redstone_block_x5>, <contenttweaker:compressed_redstone_block_x5>, <contenttweaker:compressed_redstone_block_x5>]]);
recipes.addShaped(<contenttweaker:compressed_redstone_block_x5>, [[<contenttweaker:compressed_redstone_block_x4>, <contenttweaker:compressed_redstone_block_x4>, <contenttweaker:compressed_redstone_block_x4>],[<contenttweaker:compressed_redstone_block_x4>, <contenttweaker:compressed_redstone_block_x4>, <contenttweaker:compressed_redstone_block_x3>], [<contenttweaker:compressed_redstone_block_x4>, <contenttweaker:compressed_redstone_block_x4>, <contenttweaker:compressed_redstone_block_x4>]]);
recipes.addShaped(<contenttweaker:compressed_redstone_block_x4>, [[<contenttweaker:compressed_redstone_block_x3>, <contenttweaker:compressed_redstone_block_x3>, <contenttweaker:compressed_redstone_block_x3>],[<contenttweaker:compressed_redstone_block_x3>, <contenttweaker:compressed_redstone_block_x3>, <contenttweaker:compressed_redstone_block_x3>], [<contenttweaker:compressed_redstone_block_x3>, <contenttweaker:compressed_redstone_block_x3>, <contenttweaker:compressed_redstone_block_x3>]]);
recipes.addShaped(<contenttweaker:compressed_redstone_block_x3>, [[<contenttweaker:compressed_redstone_block_x2>, <contenttweaker:compressed_redstone_block_x2>, <contenttweaker:compressed_redstone_block_x2>],[<contenttweaker:compressed_redstone_block_x2>, <contenttweaker:compressed_redstone_block_x2>, <contenttweaker:compressed_redstone_block_x2>], [<contenttweaker:compressed_redstone_block_x2>, <contenttweaker:compressed_redstone_block_x2>, <contenttweaker:compressed_redstone_block_x2>]]);
recipes.addShaped(<contenttweaker:compressed_redstone_block_x2>, [[<contenttweaker:compressed_redstone_block_x1>, <contenttweaker:compressed_redstone_block_x1>, <contenttweaker:compressed_redstone_block_x1>],[<contenttweaker:compressed_redstone_block_x1>, <contenttweaker:compressed_redstone_block_x1>, <contenttweaker:compressed_redstone_block_x1>], [<contenttweaker:compressed_redstone_block_x1>, <contenttweaker:compressed_redstone_block_x1>, <contenttweaker:compressed_redstone_block_x1>]]);
recipes.addShaped(<contenttweaker:compressed_redstone_block_x1>, [[<minecraft:redstone_block>, <minecraft:redstone_block>, <minecraft:redstone_block>],[<minecraft:redstone_block>, <minecraft:redstone_block>, <minecraft:redstone_block>], [<minecraft:redstone_block>, <minecraft:redstone_block>, <minecraft:redstone_block>]]);

//Изумрудные блоки
recipes.addShaped(<contenttweaker:compressed_emerald_block_8>, [[<contenttweaker:compressed_emerald_block_7>, <contenttweaker:compressed_emerald_block_7>, <contenttweaker:compressed_emerald_block_7>],[<contenttweaker:compressed_emerald_block_7>, <contenttweaker:compressed_emerald_block_7>, <contenttweaker:compressed_emerald_block_7>], [<contenttweaker:compressed_emerald_block_7>, <contenttweaker:compressed_emerald_block_7>, <contenttweaker:compressed_emerald_block_7>]]);
recipes.addShaped(<contenttweaker:compressed_emerald_block_7>, [[<contenttweaker:compressed_emerald_block_6>, <contenttweaker:compressed_emerald_block_6>, <contenttweaker:compressed_emerald_block_6>],[<contenttweaker:compressed_emerald_block_6>, <contenttweaker:compressed_emerald_block_6>, <contenttweaker:compressed_emerald_block_6>], [<contenttweaker:compressed_emerald_block_6>, <contenttweaker:compressed_emerald_block_6>, <contenttweaker:compressed_emerald_block_6>]]);
recipes.addShaped(<contenttweaker:compressed_emerald_block_6>, [[<contenttweaker:compressed_emerald_block_5>, <contenttweaker:compressed_emerald_block_5>, <contenttweaker:compressed_emerald_block_5>],[<contenttweaker:compressed_emerald_block_5>, <contenttweaker:compressed_emerald_block_5>, <contenttweaker:compressed_emerald_block_5>], [<contenttweaker:compressed_emerald_block_5>, <contenttweaker:compressed_emerald_block_5>, <contenttweaker:compressed_emerald_block_5>]]);
recipes.addShaped(<contenttweaker:compressed_emerald_block_5>, [[<contenttweaker:compressed_emerald_block_4>, <contenttweaker:compressed_emerald_block_4>, <contenttweaker:compressed_emerald_block_4>],[<contenttweaker:compressed_emerald_block_4>, <contenttweaker:compressed_emerald_block_4>, <contenttweaker:compressed_emerald_block_4>], [<contenttweaker:compressed_emerald_block_4>, <contenttweaker:compressed_emerald_block_4>, <contenttweaker:compressed_emerald_block_4>]]);
recipes.addShaped(<contenttweaker:compressed_emerald_block_4>, [[<contenttweaker:compressed_emerald_block_3>, <contenttweaker:compressed_emerald_block_3>, <contenttweaker:compressed_emerald_block_3>],[<contenttweaker:compressed_emerald_block_3>, <contenttweaker:compressed_emerald_block_3>, <contenttweaker:compressed_emerald_block_3>], [<contenttweaker:compressed_emerald_block_3>, <contenttweaker:compressed_emerald_block_3>, <contenttweaker:compressed_emerald_block_3>]]);
recipes.addShaped(<contenttweaker:compressed_emerald_block_3>, [[<contenttweaker:compressed_emerald_block_2>, <contenttweaker:compressed_emerald_block_2>, <contenttweaker:compressed_emerald_block_2>],[<contenttweaker:compressed_emerald_block_2>, <contenttweaker:compressed_emerald_block_2>, <contenttweaker:compressed_emerald_block_2>], [<contenttweaker:compressed_emerald_block_2>, <contenttweaker:compressed_emerald_block_2>, <contenttweaker:compressed_emerald_block_2>]]);
recipes.addShaped(<contenttweaker:compressed_emerald_block_2>, [[<contenttweaker:compressed_emerald_block_1>, <contenttweaker:compressed_emerald_block_1>, <contenttweaker:compressed_emerald_block_1>],[<contenttweaker:compressed_emerald_block_1>, <contenttweaker:compressed_emerald_block_1>, <contenttweaker:compressed_emerald_block_1>], [<contenttweaker:compressed_emerald_block_1>, <contenttweaker:compressed_emerald_block_1>, <contenttweaker:compressed_emerald_block_1>]]);
recipes.addShaped(<contenttweaker:compressed_emerald_block_1>, [[<minecraft:emerald_block>, <minecraft:emerald_block>, <minecraft:emerald_block>],[<minecraft:emerald_block>, <minecraft:emerald_block>, <minecraft:emerald_block>], [<minecraft:emerald_block>, <minecraft:emerald_block>, <minecraft:emerald_block>]]);
recipes.addShapeless(<minecraft:emerald_block> * 9, [<contenttweaker:compressed_emerald_block_1>]);
recipes.addShapeless(<contenttweaker:compressed_emerald_block_1> * 9, [<contenttweaker:compressed_emerald_block_2>]);
recipes.addShapeless(<contenttweaker:compressed_emerald_block_2> * 9, [<contenttweaker:compressed_emerald_block_3>]);
recipes.addShapeless(<contenttweaker:compressed_emerald_block_3> * 9, [<contenttweaker:compressed_emerald_block_4>]);
recipes.addShapeless(<contenttweaker:compressed_emerald_block_4> * 9, [<contenttweaker:compressed_emerald_block_5>]);
recipes.addShapeless(<contenttweaker:compressed_emerald_block_5> * 9, [<contenttweaker:compressed_emerald_block_6>]);
recipes.addShapeless(<contenttweaker:compressed_emerald_block_6> * 9, [<contenttweaker:compressed_emerald_block_7>]);
recipes.addShapeless(<contenttweaker:compressed_emerald_block_7> * 9, [<contenttweaker:compressed_emerald_block_8>]);

//Вис батареи из таумкрафта
recipes.addShaped(<contenttweaker:compressed_vis_battery_x3>, [[<contenttweaker:compressed_vis_battery_x2>, <contenttweaker:compressed_vis_battery_x2>, <contenttweaker:compressed_vis_battery_x2>],[<contenttweaker:compressed_vis_battery_x2>, <contenttweaker:compressed_vis_battery_x2>, <contenttweaker:compressed_vis_battery_x2>], [<contenttweaker:compressed_vis_battery_x2>, <contenttweaker:compressed_vis_battery_x2>, <contenttweaker:compressed_vis_battery_x2>]]);
recipes.addShaped(<contenttweaker:compressed_vis_battery_x2>, [[<contenttweaker:compressed_vis_battery_x1>, <contenttweaker:compressed_vis_battery_x1>, <contenttweaker:compressed_vis_battery_x1>],[<contenttweaker:compressed_vis_battery_x1>, <contenttweaker:compressed_vis_battery_x1>, <contenttweaker:compressed_vis_battery_x1>], [<contenttweaker:compressed_vis_battery_x1>, <contenttweaker:compressed_vis_battery_x1>, <contenttweaker:compressed_vis_battery_x1>]]);
recipes.addShaped(<contenttweaker:compressed_vis_battery_x1>, [[<thaumcraft:vis_battery>, <thaumcraft:vis_battery>, <thaumcraft:vis_battery>],[<thaumcraft:vis_battery>, <thaumcraft:vis_battery>, <thaumcraft:vis_battery>], [<thaumcraft:vis_battery>, <thaumcraft:vis_battery>, <thaumcraft:vis_battery>]]);
recipes.addShapeless(<contenttweaker:compressed_vis_battery_x2> * 9, [<contenttweaker:compressed_vis_battery_x3>]);
recipes.addShapeless(<contenttweaker:compressed_vis_battery_x1> * 9, [<contenttweaker:compressed_vis_battery_x2>]);
recipes.addShapeless(<thaumcraft:vis_battery> * 9, [<contenttweaker:compressed_vis_battery_x1>]);

mods.industrialupgrade.GenMicrochip.addRecipe(<contenttweaker:dragon_part3>, <draconicevolution:draconium_ingot>, <industrialupgrade:alloyingot:8>, <industrialupgrade:alloyingot:4>,<industrialupgrade:alloyingot>,<enderio:item_alloy_ingot:8>, 2500);
mods.industrialupgrade.AdvAlloySmelter.addRecipe(<contenttweaker:zestialorium_ingot>, <bigreactors:ingotludicrite>,<industrialupgrade:alloyingot:5>, <bigreactors:ingotcyanite>, 5000);
mods.industrialupgrade.AdvAlloySmelter.addRecipe(<contenttweaker:ingot_of_dragon_shadow_steel>, <divinerpg:shadow_bar>,<draconicevolution:draconium_ingot>, <thermalfoundation:material:160>, 5000);
mods.industrialupgrade.AdvAlloySmelter.addRecipe(<industrialupgrade:chaosingot>, <draconicevolution:draconic_ingot>, <draconicevolution:chaos_shard:3>, <avaritia:resource:2>, 5000);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:combat_thaum_metal>, <draconicevolution:draconic_ingot>, <thaumcraft:ingot>, 5000);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:ludicrite_ichor_ingot>, <bigreactors:ingotludicrite>, <thaumictinkerer:kamiresource:3>, 4500);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:vadrilium_ingot>, <industrialupgrade:itemingots:2>, <enderio:item_alloy_ingot:8>, 4000);


mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:plasma_cell>, <contenttweaker:liquid_substrate>*4, 12000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:parasite>, <contenttweaker:plasma_cell>*4, 25000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:otherworldly_charging_element>, <contenttweaker:parasite>*4, 50000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:the_chaos_crystal>, <draconicevolution:chaos_shard>*9, 1200000000);

recipes.addShapeless(<contenttweaker:philosophical_ingot>, [<projecte:item.pe_philosophers_stone>,<avaritia:resource:4>]);
recipes.addShapeless(<contenttweaker:liquid_substrate>, [<projecte:item.pe_philosophers_stone>,<contenttweaker:stag_beetle>,<contenttweaker:centipede>,<contenttweaker:tarantula>,<contenttweaker:scorpion>,<contenttweaker:mantis>,<contenttweaker:cockroach>,<contenttweaker:cuckold_beetle>,<contenttweaker:salpuga>]);
mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:soul_wither_skeleton>,<thaumictinkerer:kamiresource:1>, 1000000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:soul_enderman>,<thaumictinkerer:kamiresource>, 1000000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:soul_wither>,<contenttweaker:wither_heart>, 1000000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:soul_dragon>,<draconicevolution:dragon_heart>, 1000000000);
mods.industrialupgrade.MolecularTransformer.addRecipe(<contenttweaker:soul_guardian_of_chaos>,<draconicadditions:chaos_heart>, 1000000000);


mods.industrialupgrade.compressor.addRecipe(<contenttweaker:slag_brick>, <railcraft:dust:4>*9);
mods.industrialupgrade.compressor.addRecipe(<contenttweaker:block_of_slag_bricks>, <contenttweaker:slag_brick>*4);

mods.thaumcraft.Infusion.registerRecipe("dragon_ichor", "ICHOR", <contenttweaker:dragon_ichor>, 12, [ <aspect:spiritus> * 256, <aspect:humanus> * 128,<aspect:draco> * 64, <aspect:caeles> * 32], <thaumictinkerer:kamiresource:2>, [<draconicevolution:draconium_ingot>,<divinerpg:corrupted_shards>,<contenttweaker:shadow_ingot>,<divinerpg:corrupted_shards>,<draconicevolution:draconium_ingot>,<divinerpg:corrupted_shards>,<contenttweaker:shadow_ingot>,<divinerpg:corrupted_shards>]);		
mods.thermalexpansion.InductionSmelter.addRecipe(<contenttweaker:dragon_iridium>, <draconicevolution:draconium_block>*4,<industrialupgrade:crafting_elements:275>, 20000);
mods.thaumcraft.ArcaneWorkbench.registerShapedRecipe("dragon_ichor_ingot", "", 300, [<aspect:aer> * 24, <aspect:ignis> * 24, <aspect:terra> * 24, <aspect:aqua> * 24, <aspect:ordo> * 24, <aspect:perditio> * 24], <contenttweaker:dragon_ichor_ingot>, [[<contenttweaker:dragon_iridium>, <contenttweaker:dragon_ichor>, <contenttweaker:dragon_iridium>], 
[<contenttweaker:dragon_ichor>, <thaumictinkerer:kamiresource:3>, <contenttweaker:dragon_ichor>],
[<contenttweaker:dragon_iridium>, <contenttweaker:dragon_ichor>, <contenttweaker:dragon_iridium>]]);

mods.avaritia.ExtremeCrafting.addShaped("ultimate generator", <contenttweaker:ultimate_generator>, [ 
[<draconicevolution:generator>, <galacticraftcore:machine>, <enderio:block_franken_zombie_generator>, <enderio:block_enhanced_combustion_generator>, <enderio:block_stirling_generator>, <enderio:block_enhanced_combustion_generator>, <enderio:block_franken_zombie_generator>, <galacticraftcore:machine>, <draconicevolution:generator>],

[<galacticraftcore:machine>, <extrautils2:machine>.withTag({Type: "extrautils2:generator_survival"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_slime"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_potion"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_tnt"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_redstone"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_pink"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_ender"}), <galacticraftcore:machine>],

[<enderio:block_franken_zombie_generator>, <thermalexpansion:dynamo:5>, <thermalexpansion:dynamo:3>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:1>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:3>, <thermalexpansion:dynamo:5>, <enderio:block_franken_zombie_generator>],

[<enderio:block_enhanced_combustion_generator>, <thermalexpansion:dynamo:3>, <thermalexpansion:dynamo:4>, <contenttweaker:rose_gold_ingot>, <bigreactors:reactorcontroller>, <contenttweaker:rose_gold_ingot>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:3>, <enderio:block_enhanced_combustion_generator>],

[<enderio:block_stirling_generator>, <extrautils2:machine>.withTag({Type: "extrautils2:generator_netherstar"}), <thermalexpansion:dynamo:1>, <bigreactors:reactorcontroller>, <draconicevolution:reactor_core>, <bigreactors:reactorcontroller>, <thermalexpansion:dynamo:1>, <extrautils2:machine>.withTag({Type: "extrautils2:generator_overclock"}), <enderio:block_stirling_generator>],

[<enderio:block_enhanced_combustion_generator>, <thermalexpansion:dynamo:3>, <thermalexpansion:dynamo:4>, <contenttweaker:rose_gold_ingot>, <bigreactors:reactorcontroller>, <contenttweaker:rose_gold_ingot>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:3>, <enderio:block_enhanced_combustion_generator>],

[<enderio:block_franken_zombie_generator>, <thermalexpansion:dynamo:5>, <thermalexpansion:dynamo:3>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:1>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:3>, <thermalexpansion:dynamo:5>, <enderio:block_franken_zombie_generator>],

[<galacticraftcore:machine>, <extrautils2:machine>.withTag({Type: "extrautils2:generator"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_dragonsbreath"}),  <extrautils2:machine>.withTag({Type: "extrautils2:generator_culinary"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_death"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_enchant"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_lava"}), <extrautils2:machine>.withTag({Type: "extrautils2:generator_ice"}), <galacticraftcore:machine>],

[<draconicevolution:generator>, <galacticraftcore:machine>, <enderio:block_franken_zombie_generator>, <enderio:block_enhanced_combustion_generator>, <enderio:block_stirling_generator>, <enderio:block_enhanced_combustion_generator>, <enderio:block_franken_zombie_generator>, <galacticraftcore:machine>, <draconicevolution:generator>] ] );
recipes.addShaped(<contenttweaker:modular_tool>, [[<modularmachinery:itemmodularium>, <bigreactors:wrench>, <modularmachinery:itemmodularium>],[<thermalfoundation:wrench>, <draconicevolution:draconium_block:1>, <appliedenergistics2:certus_quartz_wrench>], [<modularmachinery:itemmodularium>, <enderio:item_yeta_wrench>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<avaritia:ultimate_stew>, [[<avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>],[<contenttweaker:pot>, <avaritia:cosmic_meatballs>, <contenttweaker:pot>], [<contenttweaker:pot>, <contenttweaker:pot>, <contenttweaker:pot>]]);
recipes.addShaped(<contenttweaker:rose_gold_block>, [[<contenttweaker:rose_gold_ingot>, <contenttweaker:rose_gold_ingot>, <contenttweaker:rose_gold_ingot>],[<contenttweaker:rose_gold_ingot>, <contenttweaker:rose_gold_ingot>, <contenttweaker:rose_gold_ingot>], [<contenttweaker:rose_gold_ingot>, <contenttweaker:rose_gold_ingot>, <contenttweaker:rose_gold_ingot>]]);
recipes.addShaped(<contenttweaker:nuclear_fusion_reactor_casing>, [[<contenttweaker:tunshilinonim_ingot>, <industrialupgrade:proton>, <contenttweaker:tunshilinonim_ingot>],[<contenttweaker:alloy_awakened_draconium_gear>, <bigreactors:reactorcasing>, <contenttweaker:alloy_awakened_draconium_gear>], [<contenttweaker:tunshilinonim_ingot>, <industrialupgrade:proton>, <contenttweaker:tunshilinonim_ingot>]]);

mods.thaumcraft.Infusion.registerRecipe("eden_warrior", "", <contenttweaker:eden_warrior>, 8, [ <aspect:spiritus> * 512, <aspect:victus> * 256,<aspect:praemunio> * 128, <aspect:humanus> * 128], <divinerpg:eden_heart>, [<divinerpg:eden_helmet>,<divinerpg:eden_chestplate>,<divinerpg:eden_leggings>,<divinerpg:eden_boots>,<divinerpg:eden_shield>,<divinerpg:eden_blade>,<divinerpg:eden_blitz>,<divinerpg:eden_bow>,<divinerpg:eden_phaser>,<divinerpg:eden_slicer>]);
mods.thaumcraft.Infusion.registerRecipe("wildwood_warrior", "", <contenttweaker:wildwood_warrior>, 8, [ <aspect:spiritus> * 512, <aspect:victus> * 256,<aspect:praemunio> * 128, <aspect:humanus> * 128], <divinerpg:wildwood_heart>, [<divinerpg:wildwood_helmet>,<divinerpg:wildwood_chestplate>,<divinerpg:wildwood_leggings>,<divinerpg:wildwood_boots>,<divinerpg:wildwood_shield>,<divinerpg:wildwood_blade>,<divinerpg:wildwood_blitz>,<divinerpg:wildwood_bow>,<divinerpg:wildwood_phaser>,<divinerpg:wildwood_slicer>]);
mods.thaumcraft.Infusion.registerRecipe("apalachia_warrior", "", <contenttweaker:apalachia_warrior>, 8, [ <aspect:spiritus> * 512, <aspect:victus> * 256,<aspect:praemunio> * 128, <aspect:humanus> * 128], <divinerpg:apalachia_heart>, [<divinerpg:apalachia_helmet>,<divinerpg:apalachia_chestplate>,<divinerpg:apalachia_leggings>,<divinerpg:apalachia_boots>,<divinerpg:apalachia_shield>,<divinerpg:apalachia_blade>,<divinerpg:apalachia_blitz>,<divinerpg:apalachia_bow>,<divinerpg:apalachia_phaser>,<divinerpg:apalachia_slicer>]);
mods.thaumcraft.Infusion.registerRecipe("skythern_warrior", "", <contenttweaker:skythern_warrior>, 8, [ <aspect:spiritus> * 512, <aspect:victus> * 256,<aspect:praemunio> * 128, <aspect:humanus> * 128], <divinerpg:skythern_heart>, [<divinerpg:skythern_helmet>,<divinerpg:skythern_chestplate>,<divinerpg:skythern_leggings>,<divinerpg:skythern_boots>,<divinerpg:skythern_shield>,<divinerpg:skythern_blade>,<divinerpg:skythern_blitz>,<divinerpg:skythern_bow>,<divinerpg:skythern_phaser>,<divinerpg:skythern_slicer>]);
mods.thaumcraft.Infusion.registerRecipe("mortum_warrior", "", <contenttweaker:mortum_warrior>, 8, [ <aspect:spiritus> * 512, <aspect:victus> * 256,<aspect:praemunio> * 128, <aspect:humanus> * 128], <divinerpg:mortum_heart>, [<divinerpg:mortum_helmet>,<divinerpg:mortum_chestplate>,<divinerpg:mortum_leggings>,<divinerpg:mortum_boots>,<divinerpg:mortum_shield>,<divinerpg:mortum_blade>,<divinerpg:mortum_blitz>,<divinerpg:mortum_bow>,<divinerpg:mortum_phaser>,<divinerpg:mortum_slicer>]);
mods.thaumcraft.Infusion.registerRecipe("halite_warrior", "", <contenttweaker:halite_warrior>, 8, [ <aspect:spiritus> * 512, <aspect:victus> * 256,<aspect:praemunio> * 128, <aspect:humanus> * 128], <variedcommodities:statuette>, [<contenttweaker:loot_boss_5>,<contenttweaker:halite_ingot>,<contenttweaker:loot_boss_7>,<contenttweaker:halite_ingot>,<contenttweaker:loot_boss_4>,<contenttweaker:halite_ingot>,<contenttweaker:loot_boss_2>,<contenttweaker:halite_ingot>,<contenttweaker:loot_boss_1>,<contenttweaker:halite_ingot>,<contenttweaker:loot_boss_3>,<contenttweaker:halite_ingot>,<contenttweaker:loot_boss_6>,<contenttweaker:halite_ingot>]);
mods.thaumcraft.Infusion.registerRecipe("statuette", "", <variedcommodities:statuette>, 12, [ <aspect:spiritus> * 1024, <aspect:victus> * 256,<aspect:praemunio> * 128, <aspect:humanus> * 128, <aspect:day> * 128, <aspect:night> * 128, <aspect:bestia> * 128, <aspect:fluctus> * 128, <aspect:infernum> * 128], <variedcommodities:heart>, [<divinerpg:ancient_entity_statue>,<divinerpg:king_of_scorchers_statue>,<divinerpg:dramix_statue>,<divinerpg:parasecta_statue>,<divinerpg:sunstorm_statue>,<divinerpg:termasect_statue>,<divinerpg:eternal_archer_statue>,<divinerpg:experienced_cori_statue>,<divinerpg:the_watcher_statue>,<divinerpg:ayeraco_statue_purple>,<divinerpg:ayeraco_statue_green>,<divinerpg:ayeraco_statue_blue>,<divinerpg:ayeraco_statue_yellow>,<divinerpg:ayeraco_statue_red>,<divinerpg:vamacheron_statue>,<divinerpg:densos_statue>,<divinerpg:reyvor_statue>,<divinerpg:soul_fiend_statue>,<divinerpg:karot_statue>,<divinerpg:twilight_demon_statue>]);

mods.thaumcraft.Infusion.registerRecipe("heart", "", <variedcommodities:heart>, 5, [ <aspect:spiritus> * 256, <aspect:victus> * 128,<aspect:sensus> * 128, <aspect:aversio> * 128, <aspect:praemunio> * 128, <aspect:desiderium> * 128, <aspect:exanimis> * 128], <contenttweaker:impure_tear>, [<divinerpg:eden_heart>,<divinerpg:wildwood_heart>,<divinerpg:apalachia_heart>,<divinerpg:skythern_heart>,<divinerpg:mortum_heart>]);


recipes.addShaped(<contenttweaker:bug_analyzer>, [[<thermalfoundation:storage:7>, <industrialupgrade:circuit:10>, <thermalfoundation:storage:7>],[<forestry:analyzer>, <contenttweaker:dragon_machine_frame>, <forestry:analyzer>], [<thermalfoundation:storage:7>, <industrialupgrade:circuit:10>, <thermalfoundation:storage:7>]]);

mods.thaumcraft.Infusion.registerRecipe("wither_skeleton_core", "", <contenttweaker:wither_skeleton_core>, 20, [ <aspect:spiritus> * 2500, <aspect:victus> * 500,<aspect:mortuus> * 250, <aspect:caeles> * 250], <contenttweaker:ultimate_generator>, [<industrialupgrade:crafting_elements:391>,<thaumictinkerer:kamiresource:1>,<avaritia:resource:4>,<thaumictinkerer:kamiresource:1>,<industrialupgrade:crafting_elements:391>,<contenttweaker:soul_wither_skeleton>,<industrialupgrade:crafting_elements:397>,<contenttweaker:soul_wither_skeleton>,<industrialupgrade:crafting_elements:391>,<thaumictinkerer:kamiresource:1>,<avaritia:resource:4>,<thaumictinkerer:kamiresource:1>,<industrialupgrade:crafting_elements:391>,<contenttweaker:soul_wither_skeleton>,<draconicevolution:wyvern_energy_core>,<contenttweaker:soul_wither_skeleton>]);

mods.thaumcraft.Infusion.registerRecipe("enderman_core", "", <contenttweaker:enderman_core>, 20, [ <aspect:spiritus> * 2500, <aspect:victus> * 500,<aspect:alienis> * 250, <aspect:caeles> * 250], <contenttweaker:ultimate_generator>, [<industrialupgrade:crafting_elements:381>,<industrialupgrade:crafting_elements:345>,<extrautils2:machine>.withTag({Type: "extrautils2:generator_ender"}),<thaumictinkerer:kamiresource>,<divinerpg:legendary_ender_eye>,<thaumictinkerer:kamiresource>,<contenttweaker:soul_enderman>,<extrautils2:machine>.withTag({Type: "extrautils2:generator_ender"}),<contenttweaker:soul_enderman>,<industrialupgrade:crafting_elements:345>,<industrialupgrade:crafting_elements:381>,<contenttweaker:soul_enderman>,<contenttweaker:dragon_ichor_ingot>,<divinerpg:ender_sword>,<draconicevolution:wyvern_core>,<divinerpg:ender_sword>,<contenttweaker:dragon_ichor_ingot>,<contenttweaker:soul_enderman>]);

mods.thaumcraft.Infusion.registerRecipe("wither_core", "", <contenttweaker:wither_core>, 20, [ <aspect:spiritus> * 2500, <aspect:victus> * 500,<aspect:auram> * 250, <aspect:caeles> * 250], <contenttweaker:wither_skeleton_core>, [<industrialupgrade:crafting_elements:391>,<contenttweaker:soul_wither>,<extrautils2:machine>.withTag({Type: "extrautils2:generator_netherstar"}),<harvestcraft:netherstartoastitem>,<extrautils2:machine>.withTag({Type: "extrautils2:generator_netherstar"}),<contenttweaker:soul_wither>,<industrialupgrade:crafting_elements:391>,<soulscraft:evildrop>,<harvestcraft:netherstartoastitem>,<soulscraft:evildrop>,<contenttweaker:wither_heart>,<soulscraft:evildrop>,<harvestcraft:netherstartoastitem>,<soulscraft:evildrop>]);

mods.thaumcraft.Infusion.registerRecipe("dragon_core", "", <contenttweaker:dragon_core>, 20, [ <aspect:spiritus> * 2500, <aspect:victus> * 500,<aspect:draco> * 250, <aspect:caeles> * 250], <contenttweaker:enderman_core>, [<contenttweaker:soul_dragon>,<industrialupgrade:crafting_elements:381>,<draconicevolution:draconium_block:1>,<extrautils2:machine>.withTag({Type: "extrautils2:generator_dragonsbreath"}),<draconicevolution:dragon_heart>,<extrautils2:machine>.withTag({Type: "extrautils2:generator_dragonsbreath"}),<draconicevolution:draconium_block:1>,<industrialupgrade:crafting_elements:381>,<contenttweaker:soul_dragon>,<industrialupgrade:crafting_elements:329>,<contenttweaker:dragon_leather>,<extrautils2:machine>.withTag({Type: "extrautils2:generator_dragonsbreath"}),<contenttweaker:dragon_bone>,<extrautils2:machine>.withTag({Type: "extrautils2:generator_dragonsbreath"}),<contenttweaker:dragon_leather>,<industrialupgrade:crafting_elements:329>]);

mods.thaumcraft.Infusion.registerRecipe("guardian_of_chaos_core", "", <contenttweaker:guardian_of_chaos_core>, 20, [ <aspect:spiritus> * 2500, <aspect:victus> * 500,<aspect:exitium> * 250, <aspect:caeles> * 250], <contenttweaker:dragon_core>, [<industrialupgrade:crafting_elements:329>,<draconicevolution:awakened_core>,<contenttweaker:soul_guardian_of_chaos>,<draconicevolution:awakened_core>,<industrialupgrade:crafting_elements:329>,<industrialupgrade:crafting_elements:429>,<harvestcraft:chaoscookieitem>,<industrialupgrade:chaosingot>,<harvestcraft:chaoscookieitem>,<draconicevolution:reactor_core>,<harvestcraft:chaoscookieitem>,<industrialupgrade:chaosingot>,<harvestcraft:chaoscookieitem>,<industrialupgrade:crafting_elements:429>]);

mods.avaritia.ExtremeCrafting.addShaped("artifact",  <variedcommodities:artifact>, [ 
[<divinerpg:ancient_entity_statue>, <divinerpg:mysterious_clock>, <divinerpg:infernal_flame>, <divinerpg:king_of_scorchers_statue>,<divinerpg:santa_helmet>,<divinerpg:sunstorm_statue>, <divinerpg:eden_block>, <divinerpg:eden_blade>, <divinerpg:experienced_cori_statue>],
[<divinerpg:horde_horn>, <divinerpg:parasecta_statue>, <divinerpg:divine_sword>, <divinerpg:ayeraco_statue_purple>,<divinerpg:santa_chestplate>,<divinerpg:wildwood_blade>, <divinerpg:eden_heart>, <divinerpg:skythern_heart>, <divinerpg:skythern_block>],
[<divinerpg:call_of_the_watcher>, <divinerpg:golden_fury>, <divinerpg:dramix_statue>, <divinerpg:ayeraco_statue_green>,<divinerpg:santa_leggings>,<divinerpg:wildwood_block>, <divinerpg:wildwood_heart>, <divinerpg:apalachia_heart>, <divinerpg:skythern_blade>],
[<divinerpg:the_watcher_statue>, <divinerpg:ayeraco_statue_blue>, <divinerpg:ayeraco_statue_yellow>, <divinerpg:ayeraco_statue_red>,<divinerpg:santa_boots>,<divinerpg:termasect_statue>, <divinerpg:apalachia_blade>, <divinerpg:apalachia_block>, <divinerpg:eternal_archer_statue>],
[<divinerpg:reyvor_statue>, <divinerpg:mortum_helmet>, <divinerpg:karot_statue>, <divinerpg:mortum_blade>,<divinerpg:twilight_demon_statue>,<divinerpg:eversight>, <divinerpg:quadrotic_lump>, <divinerpg:karos_lump>, <divinerpg:evernight>],
[<divinerpg:mortum_chestplate>, <divinerpg:halite_helmet>, <divinerpg:halite_blitz>, <divinerpg:halite_leggings>,<divinerpg:mortum_bow>,<divinerpg:dream_melon>, <divinerpg:honeychunk>, <divinerpg:dream_flint>, <divinerpg:dream_pie>],
[<divinerpg:mortum_block>, <divinerpg:halite_slicer>, <divinerpg:halite_blade>, <divinerpg:halite_phaser>,<divinerpg:mortum_block>,<divinerpg:karos_rockmaul>, <divinerpg:rock_chunks>, <divinerpg:nightmare_bed>, <divinerpg:everbright>],
[<divinerpg:mortum_leggings>, <divinerpg:halite_chestplate>, <divinerpg:halite_bow>, <divinerpg:halite_boots>,<divinerpg:mortum_blitz>,<divinerpg:dream_carrot>, <divinerpg:acid>, <divinerpg:moon_clock>, <divinerpg:dream_cake>],
[<divinerpg:densos_statue>, <divinerpg:mortum_boots>, <divinerpg:soul_fiend_statue>, <divinerpg:mortum_phaser>,<divinerpg:vamacheron_statue>,<divinerpg:everfright>, <divinerpg:arksiane_lump>, <divinerpg:heliosis_lump>, <divinerpg:everlight>] ] );

mods.thaumcraft.Infusion.registerRecipe("divine_core", "", <contenttweaker:divine_core>, 20, [ <aspect:caeles> * 2500], <contenttweaker:ultimate_generator>, [<variedcommodities:artifact>,<industrialupgrade:crafting_elements:301>,<variedcommodities:artifact>,<industrialupgrade:crafting_elements:301>,<variedcommodities:artifact>,<industrialupgrade:crafting_elements:301>,<variedcommodities:artifact>,<industrialupgrade:crafting_elements:301>]);

mods.buildcraft.AssemblyTable.addRecipe(<contenttweaker:halite_ingot>, 2500000, [<divinerpg:halite_helmet>,<divinerpg:halite_chestplate>,<divinerpg:halite_leggings>,<divinerpg:halite_boots>,<divinerpg:halite_shield>,<divinerpg:halite_blade>,<divinerpg:halite_blitz>,<divinerpg:halite_bow>,<divinerpg:halite_phaser>,<divinerpg:halite_slicer>]);


recipes.addShaped(<contenttweaker:protective_coating>*4, [[<galaxyspace:hdp:2>, <bigreactors:reactorcasing>, <galaxyspace:hdp:2>],[<bigreactors:reactorcasing>, <contenttweaker:awakened_draconium_plate>, <bigreactors:reactorcasing>], [<galaxyspace:hdp:2>, <bigreactors:reactorcasing>, <galaxyspace:hdp:2>]]);


mods.avaritia.ExtremeCrafting.addShaped("atomic coil", <contenttweaker:atomic_coil>*2, [ 
[null, null, null, null,null,null, null, null, null],
[null, null, null, null,null,null, null, null, null],
[null, null, <contenttweaker:otherworldly_charging_element>, <contenttweaker:thermal_alloy>,<bigreactors:reactorcasingcores>,<contenttweaker:thermal_alloy>, <contenttweaker:otherworldly_charging_element>, null, null],
[null, null, <contenttweaker:thermal_alloy>, <contenttweaker:alloy_awakened_draconium_gear>,<contenttweaker:nuclear_fusion_reactor_casing>,<contenttweaker:alloy_awakened_draconium_gear>, <contenttweaker:thermal_alloy>, null, null],
[null, null, <bigreactors:reactorcasingcores>, <contenttweaker:nuclear_fusion_reactor_casing>,<contenttweaker:tesla_copper_coil>,<contenttweaker:nuclear_fusion_reactor_casing>, <bigreactors:reactorcasingcores>, null, null],
[null, null, <contenttweaker:thermal_alloy>, <contenttweaker:alloy_awakened_draconium_gear>,<contenttweaker:nuclear_fusion_reactor_casing>,<contenttweaker:alloy_awakened_draconium_gear>, <contenttweaker:thermal_alloy>, null, null],
[null, null, <contenttweaker:otherworldly_charging_element>, <contenttweaker:thermal_alloy>,<bigreactors:reactorcasingcores>,<contenttweaker:thermal_alloy>, <contenttweaker:otherworldly_charging_element>, null, null],
[null, null, null, null,null,null, null, null, null],
[null, null, null, null,null,null, null, null, null] ] );

mods.thaumcraft.Infusion.registerRecipe("dragon_egg", "",<minecraft:dragon_egg>, 10, [<aspect:victus> * 256,<aspect:vitium> * 12, <aspect:caeles> * 8], <contenttweaker:otherworldly_charging_element>, [<contenttweaker:soul_dragon>,<contenttweaker:magic_alloy>,<avaritia:resource:4>,<soulscraft:manafilledcursedgold>,<contenttweaker:soul_dragon>,<soulscraft:manafilledcursedgold>,<avaritia:resource:4>,<contenttweaker:magic_alloy>,<contenttweaker:soul_dragon>,<contenttweaker:magic_alloy>,<avaritia:resource:4>,<soulscraft:manafilledcursedgold>]);

mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:rupee_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:rupee_ingot>, 2500);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:tungsten_armilite_ingot>, <industrialupgrade:itemingots:3>, <divinerpg:arlemite_ingot>, 5000);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:lamium_realmite_ingot>, <thermalfoundation:material:166>, <divinerpg:realmite_ingot>, 3750);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:shadow_enderium_ingot>, <thermalfoundation:material:167>, <divinerpg:shadow_bar>, 4000);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:evil_cobalt_ingot>, <extrautils2:ingredients:17>, <tconstruct:ingots>, 5000);

mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:iceika_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:snowflake>, 3750);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:arcana_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:arcanium>, 3750);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:eden_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:eden_soul>, 3750);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:wildwood_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:wildwood_soul>, 3750);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:apalachia_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:apalachia_soul>, 3750);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:skythern_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:skythern_soul>, 3750);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:mortum_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:mortum_soul>, 3750);
mods.industrialupgrade.AlloySmelter.addRecipe(<contenttweaker:vethea_steel_ingot>, <thermalfoundation:material:160>, <divinerpg:shiny_pearls>, 3750);

recipes.addShaped(<contenttweaker:mining_module3>, [[<contenttweaker:divine_automated_killer_casing>, <variedcommodities:artifact>, <contenttweaker:divine_automated_killer_casing>],[<variedcommodities:artifact>, <contenttweaker:sword6>.withTag({ench: [{lvl: 25 as short, id: 35 as short}], RepairCost: 1}), <variedcommodities:artifact>], [<contenttweaker:divine_automated_killer_casing>, <variedcommodities:artifact>, <contenttweaker:divine_automated_killer_casing>]]);

mods.avaritia.ExtremeCrafting.addShaped("secondary output improvements of the last smeltery", <contenttweaker:secondary_output_improvements_of_the_last_smeltery>, [ 
[<contenttweaker:last_casing>, <contenttweaker:last_casing>, <contenttweaker:last_casing>, <contenttweaker:glass_of_the_last_smeltery>,<contenttweaker:ventilation_of_the_last_smeltery>,<contenttweaker:glass_of_the_last_smeltery>, <contenttweaker:last_casing>, <contenttweaker:last_casing>, <contenttweaker:last_casing>],
[<contenttweaker:last_casing>, <contenttweaker:demonic_metal_ingot>, <contenttweaker:dragon_item2>, <contenttweaker:heater_of_the_last_smeltery>,<contenttweaker:stable_unstable_block>,<contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:dragon_item2>, <contenttweaker:demonic_metal_ingot>, <contenttweaker:last_casing>],
[<contenttweaker:last_casing>, <contenttweaker:dragon_item2>, <contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:pc_device_of_the_last_smeltery>,<contenttweaker:pc_device_of_the_last_smeltery>,<contenttweaker:pc_device_of_the_last_smeltery>,  <contenttweaker:heater_of_the_last_smeltery>,<contenttweaker:dragon_item2>, <contenttweaker:last_casing>],
[<contenttweaker:glass_of_the_last_smeltery>, <contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:pc_device_of_the_last_smeltery>, <singularities:singularity:43>,<contenttweaker:atomic_coil>,<singularities:singularity:43>, <contenttweaker:pc_device_of_the_last_smeltery>, <contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:glass_of_the_last_smeltery>],
[<contenttweaker:ventilation_of_the_last_smeltery>, <contenttweaker:stable_unstable_block>,<contenttweaker:pc_device_of_the_last_smeltery>, <contenttweaker:atomic_coil>,<draconicevolution:chaotic_core>,<contenttweaker:atomic_coil>, <contenttweaker:pc_device_of_the_last_smeltery>,<contenttweaker:stable_unstable_block>, <contenttweaker:ventilation_of_the_last_smeltery>],
[<contenttweaker:glass_of_the_last_smeltery>, <contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:pc_device_of_the_last_smeltery>, <singularities:singularity:43>,<contenttweaker:atomic_coil>,<singularities:singularity:43>, <contenttweaker:pc_device_of_the_last_smeltery>, <contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:glass_of_the_last_smeltery>],
[<contenttweaker:last_casing>, <contenttweaker:dragon_item2>, <contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:pc_device_of_the_last_smeltery>,<contenttweaker:pc_device_of_the_last_smeltery>,<contenttweaker:pc_device_of_the_last_smeltery>, <contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:dragon_item2>, <contenttweaker:last_casing>],
[<contenttweaker:last_casing>, <contenttweaker:demonic_metal_ingot>, <contenttweaker:dragon_item2>, <contenttweaker:heater_of_the_last_smeltery>,<contenttweaker:stable_unstable_block>,<contenttweaker:heater_of_the_last_smeltery>, <contenttweaker:dragon_item2>, <contenttweaker:demonic_metal_ingot>, <contenttweaker:last_casing>],
[<contenttweaker:last_casing>, <contenttweaker:last_casing>, <contenttweaker:last_casing>, <contenttweaker:glass_of_the_last_smeltery>,<contenttweaker:ventilation_of_the_last_smeltery>,<contenttweaker:glass_of_the_last_smeltery>, <contenttweaker:last_casing>, <contenttweaker:last_casing>, <contenttweaker:last_casing>] ] );

mods.thaumcraft.Infusion.registerRecipe("accelerator_infusion_matrix", "",  <contenttweaker:accelerator_infusion_matrix>, 15, [<aspect:day> * 256,<aspect:night> * 256,<aspect:machina> * 126,<aspect:permutatio> * 64,], <divinerpg:moon_clock>, [<contenttweaker:chaos_casing>,<contenttweaker:magic_alloy>,<contenttweaker:demonic_metal_ingot>,<contenttweaker:magic_alloy>,<contenttweaker:chaos_casing>,<contenttweaker:magic_alloy>,<contenttweaker:demonic_metal_ingot>,<contenttweaker:magic_alloy>,<contenttweaker:chaos_casing>,<contenttweaker:magic_alloy>,<contenttweaker:demonic_metal_ingot>,<contenttweaker:magic_alloy>,<contenttweaker:chaos_casing>,<contenttweaker:magic_alloy>,<contenttweaker:demonic_metal_ingot>,<contenttweaker:magic_alloy>]);

recipes.addShaped(<contenttweaker:core_of_creative_reservoir>, [[<avaritia:resource:6>, <contenttweaker:rose_gold_block>, <avaritia:resource:6>],[<contenttweaker:rose_gold_block>, <thermalexpansion:reservoir:4>, <contenttweaker:rose_gold_block>], [<avaritia:resource:6>, <contenttweaker:rose_gold_block>, <avaritia:resource:6>]]);
recipes.addShaped(<contenttweaker:fabricator>, [[<modularmachinery:itemmodularium>, <industrialupgrade:circuit:9>, <modularmachinery:itemmodularium>],[<industrialupgrade:circuit:9>, <forestry:fabricator>, <industrialupgrade:circuit:9>], [<modularmachinery:itemmodularium>, <industrialupgrade:circuit:9>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<contenttweaker:assembly>, [[<modularmachinery:itemmodularium>, <industrialupgrade:circuit:9>, <modularmachinery:itemmodularium>],[<industrialupgrade:circuit:9>, <buildcraftsilicon:assembly_table>, <industrialupgrade:circuit:9>], [<modularmachinery:itemmodularium>, <industrialupgrade:circuit:9>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<contenttweaker:laser>, [[<modularmachinery:itemmodularium>, <industrialupgrade:circuit:9>, <modularmachinery:itemmodularium>],[<industrialupgrade:circuit:9>, <quarryplus:laserplus>, <industrialupgrade:circuit:9>], [<modularmachinery:itemmodularium>, <industrialupgrade:circuit:9>, <modularmachinery:itemmodularium>]]);

mods.buildcraft.AssemblyTable.addRecipe(<contenttweaker:divine_automated_killer_casing>*16, 12500000, [<contenttweaker:divine_alloy>*4,<modularmachinery:blockcasing:4>*16,<contenttweaker:divine_pendant>*8,<contenttweaker:element_awa>*2,<contenttweaker:element_lud>*32,<contenttweaker:element_ir>*64,<contenttweaker:element_ir>*64,<contenttweaker:element_ir>*64]);

mods.buildcraft.AssemblyTable.addRecipe(<contenttweaker:last_casing>*32, 50000000, [<contenttweaker:chaos_casing>*32,<contenttweaker:zestialorium_ingot>*4,<avaritia:resource:4>*4,<extrautils2:ingredients:17>*4,<tconstruct:seared:3>*64,<tconstruct:seared:3>*64,<tconstruct:seared:3>*32]);

mods.buildcraft.AssemblyTable.addRecipe(<contenttweaker:last_casing>*16, 50000000, [<contenttweaker:element_cha>*24,<contenttweaker:zestialorium_ingot>*4,<avaritia:resource:4>*4,<extrautils2:ingredients:17>*4,<tconstruct:seared:3>*64,<tconstruct:seared:3>*64,<tconstruct:seared:3>*32]);


mods.avaritia.ExtremeCrafting.addShaped("alchemical_core", <contenttweaker:alchemical_core>, [ 
[null, null, null, null,null,null, null, null, null],
[null, null, <contenttweaker:ludicrite_ichor_ingot>, <contenttweaker:alloy_awakened_draconium_plate>,<contenttweaker:alloy_awakened_draconium_plate>,<contenttweaker:alloy_awakened_draconium_plate>, <contenttweaker:ludicrite_ichor_ingot>,null, null],
[null, <contenttweaker:ludicrite_ichor_ingot>, <contenttweaker:thermal_alloy>, <contenttweaker:cosminium_ingot>,<industrialupgrade:itemiucrafring:3>,<contenttweaker:cosminium_ingot>, <contenttweaker:thermal_alloy>, <contenttweaker:ludicrite_ichor_ingot>, null],
[null, <contenttweaker:alloy_awakened_draconium_plate>, <contenttweaker:cosminium_ingot>, <contenttweaker:industrial_alloy>,<contenttweaker:dragon_circuit>,<contenttweaker:industrial_alloy>, <contenttweaker:cosminium_ingot>, <contenttweaker:alloy_awakened_draconium_plate>, null],
[null, <contenttweaker:alloy_awakened_draconium_plate>, <industrialupgrade:itemiucrafring:3>, <contenttweaker:dragon_circuit>,<draconicevolution:awakened_core>,<contenttweaker:dragon_circuit>, <industrialupgrade:itemiucrafring:3>, <contenttweaker:alloy_awakened_draconium_plate>, null],
[null, <contenttweaker:alloy_awakened_draconium_plate>, <contenttweaker:cosminium_ingot>, <contenttweaker:industrial_alloy>,<contenttweaker:dragon_circuit>,<contenttweaker:industrial_alloy>, <contenttweaker:cosminium_ingot>, <contenttweaker:alloy_awakened_draconium_plate>, null],
[null, <contenttweaker:ludicrite_ichor_ingot>, <contenttweaker:thermal_alloy>, <contenttweaker:cosminium_ingot>,<industrialupgrade:itemiucrafring:3>,<contenttweaker:cosminium_ingot>, <contenttweaker:thermal_alloy>, <contenttweaker:ludicrite_ichor_ingot>, null],
[null, null, <contenttweaker:ludicrite_ichor_ingot>, <contenttweaker:alloy_awakened_draconium_plate>,<contenttweaker:alloy_awakened_draconium_plate>,<contenttweaker:alloy_awakened_draconium_plate>, <contenttweaker:ludicrite_ichor_ingot>,null, null],
[null, null, null, null,null,null, null, null, null] ] );

mods.thaumcraft.Infusion.registerRecipe("demonic_metal_ingot", "", <contenttweaker:demonic_metal_ingot>, 20, [<aspect:infernum> * 126,<aspect:exanimis> * 64,<aspect:cognitio> * 64,<aspect:volatus> * 64,<aspect:night> * 32], <contenttweaker:magic_alloy>, [<extrautils2:simpledecorative:1>,<contenttweaker:atomic_fusion>,<extrautils2:simpledecorative:1>,<contenttweaker:atomic_fusion>,<extrautils2:simpledecorative:1>,<contenttweaker:atomic_fusion>,<extrautils2:simpledecorative:1>,<contenttweaker:atomic_fusion>]);

recipes.addShaped(<extrautils2:machine>.withTag({Type: "crafttweaker:philosophical_converter"}), [[<contenttweaker:awakened_draconium_plate>, <extrautils2:machine>, <contenttweaker:awakened_draconium_plate>],[<extrautils2:machine>, <projecte:item.pe_philosophers_stone>, <extrautils2:machine>], [<contenttweaker:awakened_draconium_plate>, <extrautils2:machine>, <contenttweaker:awakened_draconium_plate>]]);
recipes.addShaped(<extrautils2:machine>.withTag({Type: "crafttweaker:chemical_factory"}), [[<thermalexpansion:machine:12>, <contenttweaker:draconium_plate>, <thermalexpansion:machine:12>],[<industrialupgrade:tank_iu>, <thermalexpansion:frame>, <industrialupgrade:tank_iu>], [<industrialupgrade:circuit:9>, <thermalfoundation:storage:6>, <industrialupgrade:circuit:9>]]);


mods.buildcraft.AssemblyTable.addRecipe(<contenttweaker:accelerator_laser_installation>, 25600000, [<buildcraftsilicon:assembly_table>*32,<appliedenergistics2:material:30>*64,<contenttweaker:dragon_circuit>*4,<bigreactors:blockludicrite>*16,<industrialupgrade:upgrades:1>*16]);

mods.buildcraft.AssemblyTable.addRecipe(<contenttweaker:dense_steel_rocket_casing>, 65000, [<galaxyspace:machineframes>,<enderio:item_material:54>,<industrialupgrade:itemdoubleplates:26>*4,<industrialupgrade:stik:10>,<industrialupgrade:compresscarbonultra>*2]);

mods.thaumcraft.Infusion.registerRecipe("zestial_belt", "", <contenttweaker:zestial_belt>, 20, [<aspect:praemunio> * 1024,<aspect:victus> * 1024,<aspect:infernum> * 1024,], <divinerpg:miners_amulet>, [<harvestcraft:minerstewitem>,<harvestcraft:minerstewitem>,<harvestcraft:minerstewitem>,<harvestcraft:minerstewitem>,<harvestcraft:minerstewitem>,<harvestcraft:minerstewitem>,<contenttweaker:zestialorium_ingot>,<contenttweaker:zestialorium_ingot>,<contenttweaker:zestialorium_ingot>,<contenttweaker:zestialorium_ingot>,<contenttweaker:zestialorium_ingot>,<contenttweaker:zestialorium_ingot>,<contenttweaker:elixir8>,<contenttweaker:elixir8>,<contenttweaker:elixir8>,<contenttweaker:elixir1>,<contenttweaker:elixir1>,<contenttweaker:elixir1>]);


mods.avaritia.ExtremeCrafting.addShaped("powerful_rocket_collector",  <contenttweaker:powerful_rocket_collector>, [ 
[null, null, null, null,null,null, null, null, null],
[null, <industrialupgrade:crafting_elements:306>, <contenttweaker:circuit1>, <industrialupgrade:crafting_elements:391>,<buildcraftsilicon:redstone_chipset:4>,<industrialupgrade:crafting_elements:391>, <contenttweaker:circuit1>, <industrialupgrade:crafting_elements:306>, null],
[null, <contenttweaker:circuit1>, <industrialupgrade:circuit:9>, <bigreactors:ingotgraphite>,<industrialupgrade:crafting_elements:445>,<bigreactors:ingotgraphite>, <industrialupgrade:circuit:9>, <contenttweaker:circuit1>, null],
[null, <industrialupgrade:crafting_elements:391>, <bigreactors:ingotgraphite>, <buildcraftsilicon:assembly_table>,<thermalexpansion:machine:11>,<buildcraftsilicon:assembly_table>, <bigreactors:ingotgraphite>, <industrialupgrade:crafting_elements:391>, null],
[null, <buildcraftsilicon:redstone_chipset:4>, <industrialupgrade:crafting_elements:445>, <thermalexpansion:machine:11>,<contenttweaker:dense_steel_rocket_casing>,<thermalexpansion:machine:11>, <industrialupgrade:crafting_elements:445>, <buildcraftsilicon:redstone_chipset:4>, null],
[null, <industrialupgrade:crafting_elements:391>, <bigreactors:ingotgraphite>, <buildcraftsilicon:assembly_table>,<thermalexpansion:machine:11>,<buildcraftsilicon:assembly_table>, <bigreactors:ingotgraphite>, <industrialupgrade:crafting_elements:391>, null],
[null, <contenttweaker:circuit1>, <industrialupgrade:circuit:9>, <bigreactors:ingotgraphite>,<industrialupgrade:crafting_elements:445>,<bigreactors:ingotgraphite>, <industrialupgrade:circuit:9>, <contenttweaker:circuit1>, null],
[null, <industrialupgrade:crafting_elements:306>, <contenttweaker:circuit1>, <industrialupgrade:crafting_elements:391>,<buildcraftsilicon:redstone_chipset:4>,<industrialupgrade:crafting_elements:391>, <contenttweaker:circuit1>, <industrialupgrade:crafting_elements:306>, null],
[null, null, null, null,null,null, null, null, null] ] );

mods.avaritia.ExtremeCrafting.addShaped("strong_rocket_stabilizer",  <contenttweaker:strong_rocket_stabilizer>, [ 
[<industrialupgrade:gear:11>, <contenttweaker:copper_stick>, <industrialupgrade:stik:12>, <industrialupgrade:stik:2>,<contenttweaker:draconium_gear>,<industrialupgrade:stik:2>, <industrialupgrade:stik:12>, <contenttweaker:copper_stick>, <industrialupgrade:gear:11>],
[<industrialupgrade:alloygear:2>, <industrialupgrade:stik:13>, <industrialupgrade:alloygear:2>, <industrialupgrade:gear:2>,<thermalfoundation:material:293>,<industrialupgrade:gear:2>, <industrialupgrade:alloygear:2>, <industrialupgrade:stik:13>, <industrialupgrade:alloygear:2>],
[<industrialupgrade:stik:12>, <thermalfoundation:material:294>, <industrialupgrade:alloygear:9>, <industrialupgrade:stik:18>,<industrialupgrade:crafting_elements:355>,<industrialupgrade:stik:18>, <industrialupgrade:alloygear:9>, <thermalfoundation:material:294>, <industrialupgrade:stik:12>],
[<industrialupgrade:gear:2>, <industrialupgrade:alloygear:2>, <industrialupgrade:stik:18>, <thermalfoundation:material:295>,<contenttweaker:draconium_rod>,<thermalfoundation:material:295>, <industrialupgrade:stik:18>, <industrialupgrade:alloygear:2>, <industrialupgrade:gear:2>],
[<contenttweaker:draconium_gear>, <industrialupgrade:stik:2>, <industrialupgrade:crafting_elements:355>, <contenttweaker:draconium_rod>,<contenttweaker:dense_steel_rocket_casing>,<contenttweaker:draconium_rod>, <industrialupgrade:crafting_elements:355>, <industrialupgrade:stik:2>, <contenttweaker:draconium_gear>],
[<industrialupgrade:gear:2>, <industrialupgrade:alloygear:2>, <industrialupgrade:stik:18>, <thermalfoundation:material:295>,<contenttweaker:draconium_rod>,<thermalfoundation:material:295>, <industrialupgrade:stik:18>, <industrialupgrade:alloygear:2>, <industrialupgrade:gear:2>],
[<industrialupgrade:stik:12>, <thermalfoundation:material:294>, <industrialupgrade:alloygear:9>, <industrialupgrade:stik:18>,<industrialupgrade:crafting_elements:355>,<industrialupgrade:stik:18>, <industrialupgrade:alloygear:9>, <thermalfoundation:material:294>, <industrialupgrade:stik:12>],
[<industrialupgrade:alloygear:2>, <industrialupgrade:stik:13>, <industrialupgrade:alloygear:2>, <industrialupgrade:gear:2>,<thermalfoundation:material:293>,<industrialupgrade:gear:2>, <industrialupgrade:alloygear:2>, <industrialupgrade:stik:13>, <industrialupgrade:alloygear:2>],
[<industrialupgrade:gear:11>, <contenttweaker:copper_stick>, <industrialupgrade:stik:12>, <industrialupgrade:stik:2>,<contenttweaker:draconium_gear>,<industrialupgrade:stik:2>, <industrialupgrade:stik:12>, <contenttweaker:copper_stick>, <industrialupgrade:gear:11>] ] );

mods.avaritia.ExtremeCrafting.addShaped("maximum_space_antenna",  <contenttweaker:maximum_space_antenna>, [ 
[null, null, null, null,null,null, null, null, null],
[null, null, null, null,null,null, null, null, null],
[null, null, <contenttweaker:compressed_iron_block_x2>, <contenttweaker:skythern_steel_ingot>,<contenttweaker:plate2>,<contenttweaker:skythern_steel_ingot>, <contenttweaker:compressed_iron_block_x2>, null, null],
[null, null, <contenttweaker:skythern_steel_ingot>, <extrautils2:terraformer:1>,<galacticraftcore:dishbase>,<extrautils2:terraformer:1>, <contenttweaker:skythern_steel_ingot>, null, null],
[null, null, <contenttweaker:plate2>, <galacticraftcore:dishbase>,<contenttweaker:dense_steel_rocket_casing>,<galacticraftcore:dishbase>, <contenttweaker:plate2>, null, null],
[null, null, <contenttweaker:skythern_steel_ingot>, <extrautils2:terraformer:1>,<galacticraftcore:dishbase>,<extrautils2:terraformer:1>, <contenttweaker:skythern_steel_ingot>, null, null],
[null, null, <contenttweaker:compressed_iron_block_x2>, <contenttweaker:skythern_steel_ingot>,<contenttweaker:plate2>,<contenttweaker:skythern_steel_ingot>, <contenttweaker:compressed_iron_block_x2>, null, null],
[null, null, null, null,null,null, null, null, null],
[null, null, null, null,null,null, null, null, null] ] );



mods.thaumcraft.Infusion.registerRecipe("elixir4", "",  <contenttweaker:elixir4>, 5, [<aspect:alkimia> * 10000,<aspect:vitreus> * 2560,<aspect:victus> * 2560,<aspect:cognitio> * 126], <contenttweaker:liquid_substrate>, [<divinerpg:arksiane_lump>,<divinerpg:rock_chunks>,<divinerpg:dream_cake>,<divinerpg:rock_chunks>,<divinerpg:arksiane_lump>,<divinerpg:rock_chunks>,<divinerpg:dream_cake>,<divinerpg:rock_chunks>,<divinerpg:arksiane_lump>,<divinerpg:rock_chunks>,<divinerpg:dream_cake>,<divinerpg:rock_chunks>,<divinerpg:arksiane_lump>]);

mods.thaumcraft.Infusion.registerRecipe("elixir10", "",  <contenttweaker:elixir10>, 5, [<aspect:alkimia> * 10000,<aspect:vitreus> * 2560,<aspect:victus> * 2560,<aspect:night> * 126], <contenttweaker:liquid_substrate>, [<divinerpg:evernight>,<divinerpg:everlight>,<divinerpg:everbright>,<divinerpg:everfright>,<divinerpg:eversight>]);

mods.thaumcraft.Infusion.registerRecipe("elixir7", "",  <contenttweaker:elixir7>, 5, [<aspect:alkimia> * 10000,<aspect:vitreus> * 2560,<aspect:victus> * 2560,<aspect:bestia> * 126], <contenttweaker:liquid_substrate>, [<avaritia:cosmic_meatballs>,<harvestcraft:bentoboxitem>,<harvestcraft:ploughmanslunchitem>,<harvestcraft:gourmetmuttonburgeritem>,<harvestcraft:stuffedduckitem>]);

mods.thaumcraft.Infusion.registerRecipe("elixir6", "",  <contenttweaker:elixir6>, 5, [<aspect:alkimia> * 10000,<aspect:vitreus> * 2560,<aspect:victus> * 2560,<aspect:motus> * 126], <contenttweaker:liquid_substrate>, [<contenttweaker:shadow_ingot>,<divinerpg:arcanium>,<bigreactors:blockludicrite>,<thaumadditions:adaminite_plate>,<avaritia:resource:2>,<industrialupgrade:blockprecious>,<industrialupgrade:blockprecious:2>,<industrialupgrade:blockprecious:1>]);

mods.thaumcraft.Infusion.registerRecipe("elixir5", "",  <contenttweaker:elixir5>, 5, [<aspect:alkimia> * 10000,<aspect:vitreus> * 2560,<aspect:victus> * 2560,<aspect:desiderium> * 126], <contenttweaker:liquid_substrate>, [<divinerpg:mysterious_clock>,<divinerpg:infernal_flame>,<divinerpg:horde_horn>,<divinerpg:call_of_the_watcher>,<divinerpg:densos_crystal>,<divinerpg:karot_crystal>,<divinerpg:twilight_demon_crystal>,<divinerpg:vamacheron_crystal>,<divinerpg:soul_fiend_crystal>,<divinerpg:reyvor_crystal>]);

mods.thaumcraft.Infusion.registerRecipe("elixir9", "",  <contenttweaker:elixir9>, 5, [<aspect:alkimia> * 10000,<aspect:vitreus> * 512,<aspect:victus> * 512,<aspect:dominator> * 126], <contenttweaker:liquid_substrate>, [<galaxyspace:gs_basic:12>,<contenttweaker:elixir6>,<thermalfoundation:material:1028>,<contenttweaker:elixir5>,<extrautils2:ingredients:17>,<contenttweaker:elixir7>]);

mods.thaumcraft.Infusion.registerRecipe("elixir3", "",  <contenttweaker:elixir3>, 5, [<aspect:alkimia> * 1024,<aspect:vitreus> * 512,<aspect:victus> * 512,<aspect:ignis> * 126], <contenttweaker:liquid_substrate>, [<contenttweaker:combat_thaum_metal>,<soulscraft:cursedgold>,<extrautils2:opinium:3>,<soulscraft:cursedgold>,<divinerpg:mortum_soul>,<soulscraft:cursedgold>,<thaumadditions:mithrillium_ingot>,<soulscraft:cursedgold>]);

mods.thaumcraft.Infusion.registerRecipe("elixir1", "",  <contenttweaker:elixir1>, 5, [<aspect:alkimia> * 1024,<aspect:vitreus> * 512,<aspect:victus> * 512,<aspect:herba> * 126], <contenttweaker:liquid_substrate>, [<divinerpg:apalachia_soul>,<soulscraft:cursedgold>,<thermalfoundation:material:295>,<soulscraft:cursedgold>,<enderio:block_alloy:8>,<soulscraft:cursedgold>,<contenttweaker:dragon_ichor_ingot>,<soulscraft:cursedgold>]);

mods.thaumcraft.Infusion.registerRecipe("elixir8", "",  <contenttweaker:elixir8>, 5, [<aspect:alkimia> * 1024,<aspect:vitreus> * 512,<aspect:victus> * 512,<aspect:vitium> * 126], <contenttweaker:liquid_substrate>,[<divinerpg:divine_shards>,<soulscraft:cursedgold>,<contenttweaker:plate2>,<soulscraft:cursedgold>,<draconicevolution:draconium_block:1>,<soulscraft:cursedgold>,<industrialupgrade:fluid_cell>.withTag({Fluid: {FluidName: "iufluidoxy", Amount: 1000}}),<soulscraft:cursedgold>]);

mods.thaumcraft.Infusion.registerRecipe("elixir2", "",  <contenttweaker:elixir2>, 5, [<aspect:alkimia> * 1024,<aspect:vitreus> * 512,<aspect:victus> * 512,<aspect:lux> * 126], <contenttweaker:liquid_substrate>,[<divinerpg:moon_clock>,<soulscraft:cursedgold>,<projecte:item.pe_covalence_dust:2>,<soulscraft:cursedgold>,<extrautils2:simpledecorative>,<soulscraft:cursedgold>,<industrialupgrade:alloygear:7>,<soulscraft:cursedgold>]);

mods.thaumcraft.Infusion.registerRecipe("divine_pendant", "",  <contenttweaker:divine_pendant>, 12, [<aspect:exanimis> * 256,<aspect:mortuus> * 126,<aspect:vitreus> * 64,<aspect:caeles> * 32,<aspect:day> * 32], <divinerpg:divine_stone>,[<divinerpg:terran_stone>,<divinerpg:molten_stone>,<minecraft:gold_block>,<divinerpg:bluefire_stone>,<divinerpg:bloodgem>,<minecraft:gold_block>,<divinerpg:ender_stone>,<divinerpg:corrupted_stone>,<minecraft:gold_block>,<divinerpg:ice_stone>,<divinerpg:jungle_stone>,<minecraft:gold_block>]);

mods.thaumcraft.Infusion.registerRecipe("dragon_fang", "",  <contenttweaker:dragon_fang>, 10, [<aspect:draco> * 126,<aspect:victus> * 32,<aspect:dominator> * 16], <contenttweaker:dragon_bone>, [<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>]);

mods.thaumcraft.Infusion.registerRecipe("dragon_scales", "",  <contenttweaker:dragon_scales>, 10, [<aspect:draco> * 126,<aspect:victus> * 32,<aspect:dominator> * 16], <contenttweaker:dragon_leather>, [<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>]);

mods.thaumcraft.Infusion.registerRecipe("dragon_horns", "",  <contenttweaker:dragon_horns>, 10, [<aspect:draco> * 126,<aspect:victus> * 32,<aspect:dominator> * 16], <contenttweaker:broken_dragon_horns>, [<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>,<contenttweaker:soul_dragon>,<contenttweaker:otherworldly_charging_element>]);

mods.thaumcraft.Infusion.registerRecipe("dragons_paw", "",  <contenttweaker:dragons_paw>, 10, [<aspect:draco> * 256,<aspect:victus> * 126,<aspect:dominator> * 16], <contenttweaker:broken_dragon_horns>, [<contenttweaker:dragon_fang>,<contenttweaker:dragon_fang>,<contenttweaker:dragon_fang>,<contenttweaker:dragon_fang>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>]);

mods.thaumcraft.Infusion.registerRecipe("dragon_skull", "",  <contenttweaker:dragon_skull>, 10, [<aspect:draco> * 256,<aspect:victus> * 126,<aspect:dominator> * 16], <minecraft:skull:5>, [<contenttweaker:dragon_horns>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>]);

mods.thaumcraft.Infusion.registerRecipe("dragon_soul", "", <contenttweaker:dragon_soul>, 15, [<aspect:draco> * 512,<aspect:dominator> * 256, <aspect:caeles> * 126,<aspect:victus> * 126], <minecraft:dragon_egg>, [<draconicevolution:awakened_core>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<contenttweaker:dragon_scales>,<draconicevolution:awakened_core>,<contenttweaker:dragons_paw>,<contenttweaker:dragons_paw>,<contenttweaker:dragons_paw>,<contenttweaker:dragons_paw>,<draconicevolution:awakened_core>,<contenttweaker:dragon_horns>,<contenttweaker:dragon_skull>,<draconicevolution:awakened_core>,<contenttweaker:dragon_fang>,<contenttweaker:dragon_fang>,<contenttweaker:dragon_fang>,<contenttweaker:dragon_fang>,<contenttweaker:dragon_fang>]);





mods.thaumcraft.Infusion.registerRecipe("infinity_с", "", <contenttweaker:infinity_crystal>, 20, [<aspect:auram> * 1024,<aspect:caeles> * 512,<aspect:praecantatio> * 512, <aspect:vitreus> * 256 ], <avaritia:resource:6>, [<avaritia:block_resource:2>,<contenttweaker:the_chaos_crystal>,<contenttweaker:the_chaos_crystal>,<contenttweaker:the_chaos_crystal>,<avaritia:block_resource:2>,<contenttweaker:the_chaos_crystal>,<contenttweaker:the_chaos_crystal>,<contenttweaker:the_chaos_crystal>,<avaritia:block_resource:2>,<contenttweaker:the_chaos_crystal>,<contenttweaker:the_chaos_crystal>,<contenttweaker:the_chaos_crystal>,<avaritia:block_resource:2>,<contenttweaker:the_chaos_crystal>,<contenttweaker:the_chaos_crystal>,<contenttweaker:the_chaos_crystal>]);

mods.thaumcraft.Infusion.registerRecipe("infinity_book", "", <contenttweaker:infinity_book>, 20, [<aspect:auram> * 1024,<aspect:caeles> * 512,<aspect:praecantatio> * 512, <aspect:vitreus> * 256,<aspect:cognitio> * 256 ], <minecraft:book>, [<avaritia:resource:6>,<avaritia:resource:6>,<avaritia:resource:6>,<avaritia:resource:4>,<avaritia:resource:4>,<avaritia:resource:4>,<contenttweaker:rose_gold_ingot>,<contenttweaker:rose_gold_ingot>,<contenttweaker:rose_gold_ingot>,<avaritia:resource:1>,<avaritia:resource:1>,<avaritia:resource:1>,<extrautils2:unstableingots:2>,<extrautils2:unstableingots:2>,<extrautils2:unstableingots:2>]);

mods.thaumcraft.Infusion.registerRecipe("cleansing_amulet", "TT_ICHOR", <contenttweaker:cleaning_amulet>, 10, [<aspect:praecantatio> * 250, <aspect:permutatio> * 125, <aspect:alienis> * 125], <thaumcraft:baubles>, [<thaumictinkerer:kamiresource:2>,<contenttweaker:pure_tear>,<minecraft:gold_ingot>,<minecraft:diamond>,<thaumcraft:salis_mundus>,<thaumictinkerer:kamiresource:2>,<contenttweaker:pure_tear>,<minecraft:gold_ingot>,<minecraft:diamond>,<thaumcraft:salis_mundus>]);

mods.thaumcraft.Infusion.registerRecipe("impure_tear", "", <contenttweaker:impure_tear>, 4, [<aspect:permutatio> * 60, <aspect:alienis> * 60], <minecraft:nether_star>, [<minecraft:ghast_tear>,<ore:gemQuartz>,<minecraft:diamond>,<thaumcraft:salis_mundus>,<minecraft:ghast_tear>,<ore:gemQuartz>,<minecraft:diamond>,<thaumcraft:salis_mundus>]);

recipes.addShaped(<contenttweaker:shadow_ingot>, [[<contenttweaker:shadow_nugget>, <contenttweaker:shadow_nugget>, <contenttweaker:shadow_nugget>],[<contenttweaker:shadow_nugget>, <contenttweaker:shadow_nugget>, <contenttweaker:shadow_nugget>], [<contenttweaker:shadow_nugget>, <contenttweaker:shadow_nugget>, <contenttweaker:shadow_nugget>]]);
recipes.addShapeless(<contenttweaker:shadow_nugget> * 9, [<contenttweaker:shadow_ingot>]);

mods.thaumcraft.Crucible.registerRecipe("shadow_nugget", "", <contenttweaker:shadow_nugget>, <minecraft:iron_nugget>, [<aspect:metallum> * 30, <aspect:tenebrae> * 25]);

